### ISSUE TITLE
Only few loads/orders are displayed in Scheduler Screen

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#100]
Currently only few loads/orders are displayed in Scheduler Screen though there are many New/InProgress/Complete/Canceled loads/orders. What is the criteria to display loads/orders in Scheduler Screen?

For instance, 8 Loads are filtered for the given search string in Loads Screen as shown below but, for the same search criteria there exists only 4 records in Scheduler Screen

![image](https://github.com/user-attachments/assets/b39580b1-46ab-41b3-ad64-cae42dc2db59)

![image](https://github.com/user-attachments/assets/a21519b3-2774-4a60-882b-1eb55605d869)

**Comment by Kumar090680** [comment]
@kv-myfuel : Please update comments once issue is fixed

**Comment by kv-myfuel** [comment]
@Kumar090680  criteria is basically 
1. your stops date and bols date must be greater then or equal to selected date 
2. past orders and loads mean before the date is selected will only come if is not assigned to any truck

**Comment by Kumar090680** [comment]
@kv-myfuel : As per your above comments, loads/orders in Scheduler screen are displayed as expected. Closing this issue

Selected 21-Oct-2024 date in Scheduler window in Scheduler screen, all loads/orders which have End Date equal to or more than 21-Oct-2024 were displayed. Also loads/orders which were not assigned to truck but, have End Dates less than 21-Oct-2024 were displayed.

Loads/orders which were not assigned to truck but, have End Dates less than 21-Oct-2024 were displayed.
![image](https://github.com/user-attachments/assets/38f2982e-a2a3-4651-b58a-adeb28f748f7)

Loads/orders which have End Date equal to 21-Oct-2024
![image](https://github.com/user-attachments/assets/2aa38502-ffc6-46a3-a0d8-26e0e453a026)

Loads/orders which have End Date  more than 21-Oct-2024
![image](https://github.com/user-attachments/assets/cee7bcf0-0c51-4a37-b122-830c970e0acc)
