### ISSUE TITLE
Start Date is accepting dates greater than End Date in Loads Screen

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#101]
Start Date is accepting date greater than End Date in Loads Screen. Please see below

![Image](https://github.com/user-attachments/assets/f75e9a8b-fbee-43ce-8ebf-4fe2895fd91a)

**Comment by kc-vamshi** [comment]
@Kumar090680 
Added start & end date validation.

**Comment by Kumar090680** [comment]
Start Date in Loads Create Screen is now not accepting past date than current date and also not accepting dates beyond End Date. Closing this issue.

**End Date is 14-Nov-2024**

![image](https://github.com/user-attachments/assets/1462d239-35f7-4133-aa4f-69c78a56a637)

**Past Dates and future dates beyond End Date in Start Date field are disabled are disabled**

![image](https://github.com/user-attachments/assets/f1e1040b-e252-4a7c-b70c-068b1a82b2cf)

![image](https://github.com/user-attachments/assets/7fc1ad9a-f03e-4ee8-bf4b-f14f0dc0db82)
