### ISSUE TITLE
Inactive Products are displayed in Truck Creation Screen

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#103]
There are only 2 active products for Gasoline Category in Product Screen but, while creating Truck, inactive product is also displayed and also able to create Truck with inactive Product. Please view below 

**Products for Gasoline Category**

![Image](https://github.com/user-attachments/assets/cbf3bc71-490c-4989-9b65-cfc231babd7c)

**Inactive Product in Truck Screen**

![Image](https://github.com/user-attachments/assets/4741ac6e-8f67-460c-8097-ad82d0a11403)

**Created Truck with inactive Product**

![Image](https://github.com/user-attachments/assets/9a63da8b-0782-4fc5-aedc-3433d3108758)

**Comment by kc-vamshi** [comment]
added is_active in query params to get only active products

**Comment by Kumar090680** [comment]
Now active products are alone available in the dropdown list while creating Truck (T2024). Closing the issue.

![image](https://github.com/user-attachments/assets/ccc80074-f3b2-4c78-81b7-fff6d2995551)
