### ISSUE TITLE
Unable to save/create the Load with instruction(s) included

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#106]
Unable to save/create the Load with instruction(s) included but, able to create Load without instructions.

**Comment by Kumar090680** [comment]
@Kodecorpui, @kv-myfuel : Able to save load with Load Instruction only but, not with Accounting and Driver Instructions (though Driver is selected).

![image](https://github.com/user-attachments/assets/a92547f0-ea06-4658-b15c-619a773246f5)

![image](https://github.com/user-attachments/assets/ef0606b5-0e60-4168-8499-44cef2615b85)

**Comment by Kumar090680** [comment]
@kv-myfuel : Please update comments once issue is fixed

**Comment by kv-myfuel** [comment]
@Kumar090680 Santhosh has fixed this issue @sbatharaju12 please update your feedbacks

**Comment by Kumar090680** [comment]
@sbatharaju12 : Please confirm if load created with all 3 (Load/Accounting/Driver) instructions are getting saved. Such that I can resume testing.

**Comment by Kumar090680** [comment]
@sbatharaju12 : I am able to save the load with instructions included but, not as expected. Please find below observations

1. Able to add **Accounting** instructions in a load but, accounting instructions are not retained post saving
2. When tried to edit **Driver** instructions, duplicate instruction is added automatically

**Comment by sbatharaju12** [comment]
@Kumar090680  i fixed issues related to instructions and added account instruction

**Comment by Kumar090680** [comment]
@sbatharaju12 : Created a load#BOL-20241028-TEST-01 and added instructions but, not working as expected. Please find below observations

1. Saved the load with Load instruction alone but, instruction is not retained after opening the load
2. Saved the load with Accounting instruction alone but, instruction is not retained after opening the load
3. Saved the load with Load and Accounting instructions alone (didn't include Driver instructions) but, instructions are not retained after opening the load
4. Saved the load with Driver instruction alone, now driver instructions are retained after opening the load along with earlier added Load and Accounting instructions and also duplicated. Please find below screenshots for reference.


**Load (BOL-20241028-TEST-01) with Driver selected**

![image](https://github.com/user-attachments/assets/026b754f-8a1e-43d2-930a-bb74be7b5448)

**Load and Accounting Instructions are duplicated**
![image](https://github.com/user-attachments/assets/27c591b0-3574-43c9-b5c0-9582655b2928)

**Comment by sbatharaju12** [comment]
@Kumar090680 
1. here above mentioned points all are UI issues @Vishnu06051999 fixed this issues
 2. instruction duplicate that i fixed now

**Comment by Kumar090680** [comment]
Created a load# **BOL-20241029-TEST-02** with all 3 (Accounting/Load/Driver) instructions and all 3 instructions are retained after saving as expected without any duplicates. Closing this issue.

**Load (BOL-20241029-TEST-02) with Driver cbn2024 selected**
![image](https://github.com/user-attachments/assets/2b9ab7f2-6e28-417b-aea9-bb3c85a12cda)

**Accounting, Load and Driver Instructions Added under Instructions Grid**
![image](https://github.com/user-attachments/assets/9f236ace-76a5-4b48-b15f-f8ade0375e05)
