### ISSUE TITLE
Default map in Order screen to show US (right now showing Germany)

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#108]

**Comment by Kodecorpui** [comment]
@lsalluri map default to show Us in all maps

**Comment by Kumar090680** [comment]
@Kodecorpui : Default map in below screens is currently displaying USA except in **Region Screen**. Please check

**Orders Screen**

![image](https://github.com/user-attachments/assets/b4d98002-2a6d-41f6-9e9d-1271df223aa8)

**Terminals Screen**

![image](https://github.com/user-attachments/assets/6a15f242-5343-4216-8e76-a0d47697ea6d)

**Scheduler Screen**

![image](https://github.com/user-attachments/assets/27851933-206b-4738-846e-7d19b8889da0)

**Region Screen**: USA Map is not default

![image](https://github.com/user-attachments/assets/be9152e7-a12c-4db5-a882-ccf8e7a98e46)

**Comment by Kumar090680** [comment]
@Kodecorpui : Still USA is not set as default map in Regions Screen.

![image](https://github.com/user-attachments/assets/fe68a27e-adc0-4d2f-8e72-75fba8d01809)

**Comment by Vishnu06051999** [comment]
@Kumar090680  i fixed the issue now properly working

**Comment by Kumar090680** [comment]
USA is now set as default map in Regions Screen. Closing the ticket.

![image](https://github.com/user-attachments/assets/ca6f1f75-6814-451d-9d63-5dc936fe2c27)
