### ISSUE TITLE
Instructions Tab in ShipTo Create Screen

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#110]
Currently there is no option to view ShipTo Instructions in UI similar to Instructions in Customer Screen.
 
When I select few ShipTo locations for few customers while creating an order, I see ShipTo instructions are getting added (which are pre-defined for the specific ShipTo) in Instructions grid. So, to cross-check if these are valid and also to verify if newly added ShipTo instructions while creating an order are reflected in ShipTo Screen, there should be a provision in ShipTo Screen to view, similar to Instructions Tab in Customers Screen

**Comment by Kodecorpui** [comment]
@lsalluri  shipto screen added Instruction tab

**Comment by Kumar090680** [comment]
I am able to view Instructions Tab in ShipTo Screen.  Awaiting fix for ticket#107 to complete testing. 

**1 instruction is available under Instructions Tab in ShipTo Screen for **Wayne County** location**

![image](https://github.com/user-attachments/assets/09ae42cb-41e0-418f-8f88-36eafe14cca5)

**Above instruction for **Wayne County** location is displayed under Instructions grid while order creation in Orders Screen**

![image](https://github.com/user-attachments/assets/d93c9bf3-a312-456e-b187-c5b82abaff67)

![image](https://github.com/user-attachments/assets/a7f86501-da35-4e35-8725-2aeb2622af10)


**New instructions for **Wayne County** location are added in Orders create screen for Order#ORD-20241025-TEST-02**

![image](https://github.com/user-attachments/assets/c7d319ac-1f21-4bad-8443-1a9cca4df6dd)

**New instruction added for **Wayne County** location for Order#ORD-20241025-TEST-02 in Orders create screen are reflected in Instructions Tab of ShipTo Screen**

![image](https://github.com/user-attachments/assets/6a2ea209-b0d1-4f99-8246-822635fb4036)

**Comment by Kumar090680** [comment]
@Kodecorpui : Default instruction type must be selected as **ShipTo** under Instructions Tab in ShipTo Screen since there wont be any other instructions available apart from ShipTo.


![image](https://github.com/user-attachments/assets/12cf680f-2fa7-4a7d-8ff1-74a42ccbe479)

**Comment by kc-vamshi** [comment]
@Kumar090680  added shipto as default value when adding a instruction in Ship To Instruction Tab.

**Comment by Kumar090680** [comment]
While adding new instruction, default instruction type is selected as **ShipTo** under Instructions Tab in ShipTo Screen

![image](https://github.com/user-attachments/assets/88c907d4-1229-44e4-b447-7ad73b8b5e0c)
