### ISSUE TITLE
Revamp inventory tab of Scheduler Screen

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#113]
**Back-End Changes** : 

1. Truck and Trailer Images are out of sync w.r.t images displayed in Scheduler window. 
2. Sorting of Trucks and Trailers must be in sync w.r.t Scheduler window. 

**Front-End Changes** : 

1. Column/field name is missing for the first column and all the check-boxes are checked by default. If there is no use of this column, can be removed totally
2. Truck column name to be renamed as Truck/Trailer
3. Column header to be frozen such that when scrolled up and down, header is visible through out
4. Values in Modified By column seems to be incorrect
5. Compartments column need to be sliced horizontally similar to Products/Product Categories/Gallons for transparency (see if this can be accommodated considering the column height)
6. Currently, compartment numbers are wrongly tied to compartments in Trucks screen
7. To view right most columns, need to traverse to the bottom of the page in order to enable horizontal scroll bar

**Comment by Kodecorpui** [comment]
@Kumar090680   Issue Fixed and deployed

**Comment by Kumar090680** [comment]
@Kodecorpui : Please work on the above mentioned front-end changes

@sbatharaju12 : Back-end changes are working as expected

1. Truck and Trailer Images are in sync w.r.t images displayed in Scheduler window. 
2. Sorting of Trucks and Trailers is in sync w.r.t Scheduler window. 

**Truck/Trailer Images and sorting order in Inventory Tab and Scheduler Window are in sync**

![image](https://github.com/user-attachments/assets/a2cf83e2-b115-4a12-991c-3d50dd010441)

**Comment by Kodecorpui** [comment]
@Kumar090680   deployed   latest

**Comment by Kumar090680** [comment]
@Kodecorpui : All required changes are implemented and as expected, except below.

Compartment numbers need to be sorted as per Trucks Screen

**Truck T1986 Compartments order in Trucks Screen **

![image](https://github.com/user-attachments/assets/7e6a578c-b0aa-4439-a81f-14d688bdbcad)

**Truck T1986 Compartments order in Inventory tab of Scheduler Screen**

![image](https://github.com/user-attachments/assets/6e42c561-b528-47b5-a428-7db033ab73d7)

**Comment by Kumar090680** [comment]
Compartment numbers are sorted as per Trucks Screen. Working as expected. Closing this issue

**Truck T1986 Compartments order in Trucks Screen **

![image](https://github.com/user-attachments/assets/82edd1e5-a2e7-4e09-bb4e-51295b106988)

**Truck T1986 Compartments order in Inventory tab of Scheduler Screen**

![image](https://github.com/user-attachments/assets/865cce71-7360-4f2d-a558-eb018585c38b)
