### ISSUE TITLE
Add Internal Terminal checkbox to Terminal grid and form in Terminals Screen

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#114]
Add "Internal Terminal" checkbox to Terminal grid and form in Terminals Screen

**Comment by Kodecorpui** [comment]
@Kumar090680   check box added list grid and form

**Comment by Kumar090680** [comment]
@Kodecorpui : Internal Terminal Check-box is available in both Grid/Home Page and Form/Create Page of Terminals Screen but, check-box icon is displayed after refreshing the screen only and also unable to select check-box.

![image](https://github.com/user-attachments/assets/c3313dfa-9487-4cd8-ad6c-95189e5c3e03)

![image](https://github.com/user-attachments/assets/87713f67-5ac2-41d0-822f-261f90c5dc17)

**Comment by Vishnu06051999** [comment]
@Kumar090680 as of now  internal terminal checkbox just showing in terminal edit screen

**Comment by Kumar090680** [comment]
Internal Terminal check-box is displayed in both Grid/Home Page and Form/Create Page of Terminals Screen. Currently check-box is made available only for display but, selection is not enabled. Issue can be closed.
