### ISSUE TITLE
Chat screen is not opening in web app

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#115]
Chat screen is not opening in web app

**Comment by kc-vamshi** [comment]
migrated chats from legacy app.

**Comment by Kumar090680** [comment]
Chat screen opened when **Chat with Drivers** button at the bottom of the web page is clicked and also chat screen opened while working in different screens of the web page. Closing the ticket


![image](https://github.com/user-attachments/assets/eadb166a-2bda-400d-aa53-d8e5e1c83574)

![image](https://github.com/user-attachments/assets/e7721b92-ed40-43b6-b3c1-1970b066f38c)

**Chat Screen opened while in Loads Screen**
![image](https://github.com/user-attachments/assets/c659852c-e019-4d5d-bdd4-64478334b13c)

**Chat Screen opened while in Trucks Screen**
![image](https://github.com/user-attachments/assets/3ccbdbb2-fef4-4bf2-af09-f433db722a78)
