### ISSUE TITLE
Capacity & Current Gross validation in a Truck's compartment

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#116]
Capacity & Current Gross validation in a Truck's compartment

**Comment by kc-vamshi** [comment]
@Kumar090680  Added capacity & gross validation.

**Comment by Kumar090680** [comment]
@Kodecorpui : Please find below observations

1. Current Net value is accepting more value than Current Gross but, it must not accept since, Net must always be less than Gross
2. Current Net value is not accepting less value than Current Gross but, it must accept as this value is within 5% of the Current Gross
3. Current Gross must not exceed more than Capacity value since, Capacity is the upper limit in any truck's compartment

![image](https://github.com/user-attachments/assets/8059eee5-a650-4333-af00-56dbddaf54c0)

Current Net value is accepting more value than Current Gross but, it must not accept since Net must always be less than Gross

![image](https://github.com/user-attachments/assets/8ad9f20e-01bc-469a-a6c2-f26cbaf61c7c)

Current Net value is not accepting less value than Current Gross but, it must accept as this value is within 5% of the Current Gross

![image](https://github.com/user-attachments/assets/2ec92df0-2c63-4334-9ba2-7fa31555917d)

**Comment by Vishnu06051999** [comment]
@Kumar090680  fixed that issue

**Comment by Kumar090680** [comment]
Considering USA climatic conditions, 5% buffer is allowed. Current Gross can accept 5% more than the Capacity, similarly Current Net can accept 5% more than the Current Gross (which are already the existing limits). Hence, closing the ticket.

![image](https://github.com/user-attachments/assets/f2207157-cf68-434c-9442-46460a5cc0f6)
