### ISSUE TITLE
Order changes with assets grid

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#123]
Default gross and net with compartment's capacity in the assets grid
Capacity dropdown should not be editable in the assets grid
Compartments should be ascending in the assets grid

**Comment by manju45kk** [comment]
HI @lsalluri  -changes are done avilable in env.

**Comment by Kumar090680** [comment]
@sbatharaju12 : Products associated with Category are not displayed in Add Product grid in Order Screen. Please check.

**Comment by Kumar090680** [comment]
@manju45kk : Please find below observations

1. Default gross and net with compartment's capacity in the assets grid - **When Add all Truck Compartments and All all Trailer Compartments check-boxes are checked, compartment details are not getting added in the Asset Grid**

2. Capacity dropdown should not be editable in the assets grid - **Capacity is editable. Please fix the issue**

3. Compartments should be ascending in the assets grid - **I selected **T1986** truck which has 4 compartments. When tried to add all 4 compartments by clicking **Add all Truck Compartments**, error is thrown so, truck compartments are not imported. Please fix the issue**

4. All the asset details were disappeared after saving the order

**Comment by manju45kk** [comment]
Cnages are done -
