### ISSUE TITLE
Associated BOL logic for assets grid in order screen

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#125]
When assigned truck is selected
filter the lookup BOl to only show the BOLS associated with that truck
When BOL is associated  then add those product category specific details when add all truck rows are clicked, if individual rows are clicked only show the associated BOL related data as an option
send associated BOL ID with compartment API, if BOL exists then only send back that details for filter
If add all truck rows are not clicked then only allow the selection from the associated BOL

**Comment by sbatharaju12** [comment]
fixed this issue 
@UI they need to send assigned_truck as a query_params then they will get all asosiated truck BOLs

**Comment by Kumar090680** [comment]
@manju45kk : Currently all BOLs are listed irrespective of the selected assigned truck. Please check

**Assigned Truck for this order ORD-20241108-TEST-01 is T1980**
![image](https://github.com/user-attachments/assets/3b6bfa24-4aec-4918-ba56-396f3b7c536c)


**All BOLs irrespective of assigned truck are displayed under Product Grid**
![image](https://github.com/user-attachments/assets/ff595d68-a52e-4a6a-8680-ac9735f9075b)

**BOL 407 has truck T006 assigned but, this BOL is displayed when Add BOL is clicked**
![image](https://github.com/user-attachments/assets/f0b5bc63-0a05-4cf6-9548-804bb2099ed7)

**Comment by kc-vamshi** [comment]
@Kumar090680
awaiting BOL minimal api from @sbatharaju12.

**Comment by kc-vamshi** [comment]
@Kumar090680 When a truck, trailer, or both are assigned, BOLs are generated based on the truck. If only a trailer is assigned, BOLs are generated based on the trailer. When both are empty getting all the BOL's.
