### ISSUE TITLE
When truck or trailer is assigned in a load or order show the assigned truck as a hyperlink and show the truck details

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#129]

**Comment by kc-vamshi** [comment]
Added Truck and Trailer Preview for Order.

**Comment by Kumar090680** [comment]
Working as expected. Closing this issue.

[#129 - When truck or trailer is assigned in a load or order show the assigned truck as a hyperlink and show the truck details.docx](https://github.com/user-attachments/files/17635950/129.-.When.truck.or.trailer.is.assigned.in.a.load.or.order.show.the.assigned.truck.as.a.hyperlink.and.show.the.truck.details.docx)
