### ISSUE TITLE
Name must be unique in Assets Screen

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#132]
1. Name must be unique in Assets Screen. Currently, this field is accepting duplicate names.
2. Name field in Assets Screen is accepting space and hyphen(-) only but, the same Name field while creating from ShipTo Screen is  accepting space and all special characters. Same limitations need to be enforced in both the screens for the same Name field.

**Comment by Kumar090680** [comment]
@sbatharaju12 : Please work on the #1 mentioned in the ticket description

@Kodecorpui : Please work on the #2 mentioned in the ticket description

**Comment by sbatharaju12** [comment]
@Kumar090680 i have completed unique name in Assts

**Comment by Kumar090680** [comment]
@kc-vamshi : As discussed, please implement the above change.

**Comment by kc-vamshi** [comment]
@Kumar090680 Implemented Asset Name field restriction in Shipto's Asset Tab same as Asset Create Screen

**Comment by Kumar090680** [comment]
@kc-vamshi : Asset Name created in ShipTo Screen is still accepting special characters. And also, Name and Number fields are accepting spaces as the first character in both Assets Create Screen and ShipTo Add Asset Screens. Please check below and fix it.

![image](https://github.com/user-attachments/assets/f835800c-dcc5-4109-9ba9-77d9145e3695)

**Comment by kc-vamshi** [comment]
@Kumar090680 added validation in asset popup and shipto- asset tab as well.

**Comment by Kumar090680** [comment]
@kc-vamshi : Asset names are accepting duplicate values whether created directly in Assets Screen or from ShipTo Screen. Also, Asset created from ShipTo screen is accepting space as the first character for Asset Name.


![image](https://github.com/user-attachments/assets/3b454c42-5022-4a32-b267-d3d53ce2540a)

**Comment by kc-vamshi** [comment]
@Kumar090680 
1. An error is displayed when an asset with the same name already exists in the Asset screen, but the backend does not validate this for the ShipTo screen.  
2. The asset name input now behaves the same in both the ShipTo and Asset screens.

**Comment by Kumar090680** [comment]
@sbatharaju12 : As discussed, can you restrict duplicate entry(Asset Name) creation from ShipTo Screen? Assigning this ticket to you for integrating with API.

**Comment by sbatharaju12** [comment]
@Kumar090680 this issue was resolved 
![Image](https://github.com/user-attachments/assets/d02ca128-6e1e-4654-a90b-3b429326fe3f)

**Comment by Kumar090680** [comment]
Now error is displayed if duplicate asset entry is added from ShipTo Screen also. Working as expected

**ShipTo Screen**
![image](https://github.com/user-attachments/assets/4ef60e68-0a5a-4af1-8084-41b2a3313a8d)

**Asset Screen**
![image](https://github.com/user-attachments/assets/6dd903e1-d1f7-4618-99da-8d46eceb9ca9)
