### ISSUE TITLE
Completed load is clearing the assigned truck

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#141]
![Image](https://github.com/user-attachments/assets/994d1736-837b-4052-b71a-d8d5c8093a71)

**Comment by Vishnu06051999** [comment]
@lsalluri actually  make the all validation from UI side when we complete the load according to truck assign with error message may be record has updated from Mobile Side

**Comment by Kumar090680** [comment]
@lsalluri : I verified **BOL ID - 380** which was mentioned in the above image and this BOL was created from Mobile but, not from Web. Moreover all loads which were completed from Web have Assigned Truck/Trailer intact. Probably, Assigned Truck is not made mandate while completing load from Mobile. Closing this issue.

**BOL ID - 380 not available in Web**
![image](https://github.com/user-attachments/assets/a2bbe4da-4e15-41b1-a3bf-a65f32d36b19)

**BOL ID - 395 completed load with Assigned Truck and Assigned Trailer intact in Web**
![image](https://github.com/user-attachments/assets/f0f9c4f8-78b1-4831-b3b0-cd56b5f00dd9)

![image](https://github.com/user-attachments/assets/15cc8ab7-4f7b-480f-b21c-505ad85d7168)

**Comment by lsalluri** [comment]
This is back ![Image](https://github.com/user-attachments/assets/a7bf35e4-2fb3-4bbb-856b-e8e0b7987d95)

**Comment by Kumar090680** [comment]
@lsalluri : I created a **BOL ID#429** in **admin@myfuel.ai** login and **BOL ID#434** in **suncoast@myfuel.ai** login with assigned truck, trailer and completed BOLs. All details were intact without any issue as shown below. 


**BOL ID#429 completed with Truck and Trailer details intact in admin@myfuel.ai login**

![image](https://github.com/user-attachments/assets/bb1c858c-a51e-476a-a7db-ce2a20a1c789)
![image](https://github.com/user-attachments/assets/d16f3dde-94b5-4c57-865e-fdf342a6678e)

**BOL ID#434 completed with Truck and Trailer details intact in suncoast@myfuel.ai login also**

![image](https://github.com/user-attachments/assets/391f1dcf-9a64-4f58-aa57-42a18fbaeb91)
![image](https://github.com/user-attachments/assets/044263d2-aeaa-45cd-9172-5567f1f7e3b7)
