### ISSUE TITLE
Assets need to auto populate (if 1 exists or provide dropdown to select if multiple exists + be able to type out a new asset if needed) when I add compartments from a truck or trailer

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#144]
Added gasoline to truck SC001, then added all compartments, it correctly only showed compartments with gasoline. When I tried to select an asset, it is giving me the typing cursor inatead of dropdown with asset choices. When I try to click out of the row or delete I am getting a capacity error.

Change needed: If I add truck rows, and if only 1 asset exists in that location then auto populate that asset information. If there is more than 1 asset then provide a dropdown for me to change the asset. Capacity also needs to be auto-populated when asset is chosen.

When I save with this information, I am getting a 400 error.

Also, if product category is changes after asset is added/saved then show "Are you sure you want to edit the requested products category or product? This will clear any existing assets that are being added."

Change existing wording for truck and trailer Are you sure you want to remove all truck rows or trailer rows.

**Comment by lsalluri** [comment]
This this point to another ticket: also, if product category is changes after asset is added/saved then show "Are you sure you want to edit the requested products category or product? This will clear any existing assets that are being added."

**Comment by Kumar090680** [comment]
@lsalluri : As @manju45kk confirmed some changes are pending to be implemented so, parking aside this ticket for now until changes are implemented. Assigning back to @manju45kk

**Comment by Kumar090680** [comment]
@lsalluri : All the required functionalities are available as expected.


**Compartments in Truck T1986**
![image](https://github.com/user-attachments/assets/584ab361-7733-4a43-9bf3-51f2dd72bd55)


**Assigned Truck T1986**
![image](https://github.com/user-attachments/assets/8e6a0008-b695-4826-ba2d-9fdd4aad3b52)

**Matched Assets in ShipTo Location - Miami Court**
![image](https://github.com/user-attachments/assets/9033d807-09db-41bb-b55a-67cfbc1b3af6)

**Single Asset that matched selected product in the truck (T1986)'s compartment was auto selected in Fueling Events grid**
![image](https://github.com/user-attachments/assets/b36fdfa6-e9d4-495a-b722-12d4718dd3ee)

**Multiple Assets that matched selected product in the truck (T1986)'s compartment was auto selected in Fueling Events grid**
![image](https://github.com/user-attachments/assets/145a15db-29b6-44de-a8ef-4994e39c64b1)
![image](https://github.com/user-attachments/assets/45f245c1-aa3d-4e97-96a2-70fb80569578)

**Added new asset FE-LFT-Miami Court-03 (Which was not available in ShipTo Miami Court) from Assets Grid**
![image](https://github.com/user-attachments/assets/ddc33444-5b88-4c2e-bb44-4aff6d665c47)

**Newly added asset FE-LFT-Miami Court-03 from Assets Grid is now available under ShipTo Miami Court in ShipTo Screen**
![image](https://github.com/user-attachments/assets/5e94042e-1064-4957-b77a-f0a0f1a36b43)

**Confirmation message when the requested product/category is changed. I changed from Diesel Category to Lubricants**
![image](https://github.com/user-attachments/assets/41843e17-2a42-40d9-b6a2-491b74b82134)

**Existing assets were cleared once above confirmation message is accepted**
![image](https://github.com/user-attachments/assets/16cafcbd-71c9-40a9-a0b8-42f2a6695d9d)
