### ISSUE TITLE
Truck sliding figma design

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#149]
Please implement this new design: https://www.figma.com/design/nPRRAc0cqFDt8AAl7JGu2P/K%26Z-Myfuel.ai?node-id=12251-43069&node-type=instance&t=1Ti8yWKgoJCRImnw-0

**Comment by Kumar090680** [comment]
@SaiAkhil2 : Please find my below observations and update the design

1. Text must be in uppercase similar to BOL preview sliding feature as shown below
2. Icon used to represent Compartments in Truck sliding feature is used  in Scheduler Screen to represent Trailer as shown below so, better to remove icon for compartments and retain for Truck alone
3. To show Trailer Sliding feature, need to show Trailer icon so, cannot use the same icon for Compartments also.


@lsalluri  : Thoughts please.

**Current BOL load preview sliding feature**
![image](https://github.com/user-attachments/assets/f113b04f-75dc-47f4-9b0d-502356a923d6)

**Trailer Icon in Scheduler Screen**
![image](https://github.com/user-attachments/assets/5247747a-e087-4114-9e28-e351761225de)

**Truck sliding feature as below**
![image](https://github.com/user-attachments/assets/9231942d-76ff-44b1-beb6-3a2a8849c06c)

**Comment by Kumar090680** [comment]
@SaiAkhil2 : Truck Sliding feature and Trailer Sliding feature windows have same name as TRUCK INFO, need to update as TRAILER INFO when assigned trailer is clicked and also icon to be changed. Please refer below images for reference


**Trailer Sliding Feature**
![image](https://github.com/user-attachments/assets/3604551d-3ac7-49da-9358-7c320392dbe5)

**Truck Sliding Feature**
![image](https://github.com/user-attachments/assets/7014f671-8d9d-4d72-b7b0-abe6c0dd54cc)

**Comment by Kumar090680** [comment]
@lsalluri : Truck and Trailer info in Truck sliding window in Loads and Orders screen are as expected.

**Truck and Trailer Info in Loads Screen**
![image](https://github.com/user-attachments/assets/f6cc8558-7e74-405c-8561-330cf105d21e)
![image](https://github.com/user-attachments/assets/782a355c-3ba6-48f5-b52c-0b15e2352c68)

**Truck and Trailer Info in Orders Screen**
![image](https://github.com/user-attachments/assets/a0669171-d200-482c-815f-10d57d71d6ff)
![image](https://github.com/user-attachments/assets/f098159e-4695-41d3-a211-1db5c500277e)
