### ISSUE TITLE
Assets Create Screen is displaying all available ShipTos irrespective of selected Customer

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#151]
Currently while creating an asset, all ShipTos are displayed in the dropdown list irrespective of the selected Customer. Displaying all ShipTos is valid only if no Customer is selected but, if Customer is selected, only relevant ShipTos must be displayed in the dropdown.

**Comment by Kumar090680** [comment]
When Customer is not selected, all ShipTos are displayed and specific ShipTo is only displayed when Customer is selected. Working as expected in QA env.

**All ShipTos When No Customer is selected:**

![image](https://github.com/user-attachments/assets/e4c2c774-3151-467b-a503-f97d647a20d6)

**Specific ShipTo is displayed when Customer is selected:**

![image](https://github.com/user-attachments/assets/776c3644-fb46-4f09-a660-eb244aefc39a)

![image](https://github.com/user-attachments/assets/49e1ec0e-e891-4214-94f5-cb7bbac5c558)
