### ISSUE TITLE
When load is completed we need to show completed loads by default and give checkbox "Show Requested Loads" to show the requested section, right now it's showing opposite and truck information is clearing for a completed load

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#155]
![Image](https://github.com/user-attachments/assets/5f5a7bcb-2001-4b4f-981f-54dd32063ad0)
 see load 1171124 for suncoast@myfuel.ai, myfuelai2024

**Comment by Kumar090680** [comment]
@lsalluri : All below listed functionalities are working as expected, closing this ticket

1. Assigned Truck and Assigned Trailer are retained without disappearing upon completion of BOL/Load as shown in below image
2. Completed Loads table is displayed in Add Product grid once load is completed
3. Show Requested Loads check-box is available and when checked, requested loads are displayed adjacent to completed loads under Add Product grid as shown below


**Assigned Truck and Assigned Trailer are retained without disappearing upon completion of BOL/Load**
![image](https://github.com/user-attachments/assets/411e1fca-8d81-4715-92f0-98c755a90540)

**Requested loads are displayed adjacent to completed loads**
![image](https://github.com/user-attachments/assets/8f3a3426-a1d5-48d3-a489-456593dffb7b)
