### ISSUE TITLE
When I open document or image on a completed load or order, open in new tab. Right now its opening in same tab and if i click back it is taking me back to main BOL grid screen

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#156]

**Comment by SaiAkhil2** [comment]
![Image](https://github.com/user-attachments/assets/6a266a05-a948-4b7a-ac10-e868957f4ef7)
Actually, it creates a preview of the image, but the buttons were previously invisible. Now, the user can see the buttons, and it has ZoomIn and ZoomOut capabilities as well as document rotation.  @lsalluri

**Comment by Kumar090680** [comment]
@lsalluri : Image uploaded while completing a BOL is displayed in the same tab with close button at the right top corner. Zoom-in, Zoom-out, clock-wise and anti clock-wise buttons are working as expected. Closing the issue

**BOL-20241111-TEST-03**
![image](https://github.com/user-attachments/assets/fd1ad2ca-861a-426c-9cf2-e6616f0f1742)

![image](https://github.com/user-attachments/assets/3c936c98-b409-4825-914b-1a890f25e084)

**Uploaded images opened in same tab with close button**
![image](https://github.com/user-attachments/assets/46957cf0-ee65-4d7d-836e-0fc9d9e262ee)

**Clock-wise and Anti-clockwise buttons**
![image](https://github.com/user-attachments/assets/be93b11c-6b28-4e5c-8f6c-1822b944dfa8)
![image](https://github.com/user-attachments/assets/315e5f1f-2b5f-4ecc-a666-a93f6c53eee3)
