### ISSUE TITLE
When I created order I had some customer and ship to requirements checked and when I click back into the order it is all gone. This specific order had purchase order checked along with some others.

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#157]
![Image](https://github.com/user-attachments/assets/b2c58c15-bde7-4ff2-8fc8-2657499cef2a)

![Image](https://github.com/user-attachments/assets/77b76018-f796-4e10-8b04-ee53ab95a94c)

**Comment by Kumar090680** [comment]
@lsalluri : Created an order **ORD-20241108-TEST-02** with customer and ship to requirements. Both these requirements are retained after saving and opening back. Working as expected, closing this issue


**Order created and saved with Customer and ShipTo requirements checked. Please check the timestamp highlighted in the below image**
![image](https://github.com/user-attachments/assets/24580198-8f16-4ec8-8117-519bc510b15e)

**Same Order is opened again after few minutes and all Customer and ShipTo requirements are still checked. Please check the timestamp highlighted in the below image**
![image](https://github.com/user-attachments/assets/26433e1d-dc11-4693-a2b3-05d2b94f9313)
