### ISSUE TITLE
In load screen if there is 0 gross and net gallons in a compartment then I should be able to change the category and product of the requested load section

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#158]
In load screen if there is 0 gross and net gallons in a compartment then I should be able to change the category and product of the requested load section

Right now if the requested load was defaulted to CONV89OCT it is only allowing me to change to CONV89OCT and CONV91OCT, because there are 0 gallons in the gross and net compartment details, I should be able to choose any category and any products in the category regardless of product variants.
![Image](https://github.com/user-attachments/assets/b7d4681c-2ab8-4d3a-bf75-a71326134ebb)

**Comment by Kodecorpui** [comment]
@lsalluri   Issue Fixed

**Comment by Kumar090680** [comment]
@lsalluri : Working as expected. Please refer below screenshots.


**When 0 gross and 0 net gallons exists in a truck's compartment then, Product Category and Product are editable**

![image](https://github.com/user-attachments/assets/7dad11b2-d556-43fd-a445-1296fae92e9c)
![image](https://github.com/user-attachments/assets/625e269e-ae92-4a05-89e3-bcafac906be2)

**When 0 gross and 0 net gallons exists in a trailer's compartment then, Product Category and Product are editable**

![image](https://github.com/user-attachments/assets/782d16f8-89ea-4ae4-a1c5-25e4f8dfaf87)
![image](https://github.com/user-attachments/assets/a93175be-86d6-46f7-a3e1-bc49fe0974a6)
