### ISSUE TITLE
Show the oldest completed items last for example 403 was completed first so it should be last on the list and then 404

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#161]
![Image](https://github.com/user-attachments/assets/347bce5e-322a-4bba-a355-c3dcead2563a)

**Comment by rbandarukodecorp** [comment]
@sbatharaju12 Please provide modified param from device ping api for both Load and Order

**Comment by lsalluri** [comment]
@rbandarukodecorp  This is not working. For  example Load 497 was created first and modified. I then created 114234 which means I modified after 497 so it should come above load 497. I think it is showing opposite.

I also think it can't be based on modified date because if I try to edit 497 then the modified date will change. We need to take the created date. and show the most recently created ones at the top. similarily we need to show the most recently completed ones at the top (of the completed section).

![Image](https://github.com/user-attachments/assets/198924b0-65d3-4fa5-9136-c4a0b76e579d)
