### ISSUE TITLE
When a load or delivery is complete, the truck inventory is updating the current gross and current net but not the product category and product name in the truck compartments

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#169]
BOL 404 was completed and I loaded Gasoline CONV91 into all compartments but truck is still showing 

suncoast@myfuel.ai, myfuelai2024
![Image](https://github.com/user-attachments/assets/bc4e6b2f-f6db-4ee9-9055-a83e6f14c0f7)
![Image](https://github.com/user-attachments/assets/33d76e25-1fe8-4b50-ad9d-4a820cf492f2)

**Comment by sbatharaju12** [comment]
@lsalluri  this one is fixed now we are updating compartments based on bol actual product
