### ISSUE TITLE
Duplicate assets when trying to add new fueling event

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#173]
![Image](https://github.com/user-attachments/assets/26a328a8-a347-4bf3-ae56-fc10924a052f)

**Comment by lsalluri** [comment]
Still seeing the same issue. Waiting on Santosh to fix it ![Image](https://github.com/user-attachments/assets/700e6688-fd29-496e-b25c-de537d3fe977)

**Comment by sbatharaju12** [comment]
@lsalluri as per our previous discuession from mobile side they need to add one key(number) 
for duplicate asset names need to add asset tank number like HGA01(01)

**Comment by durgaprasadkodecorp** [comment]
@lsalluri I connected with Santosh for this issue in API we are getting the number as a null value it will bind the asset name as a duplicate with the respective name and product and the number should not be the null value.
