### ISSUE TITLE
Why is product being restricted when compartment has 0 gallons?

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#176]
![Image](https://github.com/user-attachments/assets/e6cb3175-1ab5-4f95-a2b5-7ae1d6051b78)

In this row, the capacit is 0 so I should be able to edit the product category and the product, which is working as expected but I am not seeing all of the products for diesel here. ULSD #2 is missing. Why?

I already had diesel ULSD #1 selected but when I saved the second row and went back tochange the product in the first row, I am seeing ULSD #1 for gasoline instead of the gasoline products.

![Image](https://github.com/user-attachments/assets/6df1785d-2883-45b1-80cd-16c6c4b1d053)

**Comment by Kumar090680** [comment]
@lsalluri : When Gross and Net are 0, I am able to edit/select both product category and product values from dropdown list values. This similar issue is already tested and closed. Please refer #158. Working as expected, closing this issue

**BOL-20241113-TEST-01 with T2024 truck**
![image](https://github.com/user-attachments/assets/d00c5220-b66f-4916-8acc-a5d4fbb4afa1)

**Editable Categories**
![image](https://github.com/user-attachments/assets/2c858fd8-4df0-4001-9fbe-6d34c3a1e36b)

**Editable Products**
![image](https://github.com/user-attachments/assets/2c9f33cb-d8f5-4c78-9676-a0333007bcd9)

**Selected Gas Fuel and ULSD #345**
![image](https://github.com/user-attachments/assets/6c46d2d3-90b1-4f6f-8d5f-feed77d80ea1)

**Saved first record (in compartment #1) and went back to second record which has 0 Gross and 0 Net, I am able to view related products for the selected Gasoline category**
![image](https://github.com/user-attachments/assets/06767b08-b344-489d-aeeb-1bd167e71004)
![image](https://github.com/user-attachments/assets/f8d5a4ce-9fc1-4e1a-8204-835af9aa5abe)

**Products for Gasoline Category**
![image](https://github.com/user-attachments/assets/05b6ef55-be47-4c7c-9b62-2705d7a101a0)
