### ISSUE TITLE
Note that I added as a driver in the mobile app is showing as a load instruction instead of driver instruction. Any note coming in from the app for load or order should show as driver instruction.

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#178]
![Image](https://github.com/user-attachments/assets/a59a7aa2-a6a6-4c5b-a3e1-bab90b92374a)

For load 417, suncoast@myfuel.ai, myfuelai2024

**Comment by kc-vamshi** [comment]
@lsalluri from API itself they are sending instruction type as Load, need to change from backend side.

**Comment by sbatharaju12** [comment]
@lsalluri from mobile they are not sending driver while completing the load thats why driver instructions are not retained back  @lbandarukodecrop fixed this issue

**Comment by Kumar090680** [comment]
@lsalluri  : Instruction grid to be revamped as per comments updated in #97. Probably, this can be tested if #97 is implemented.

**Comment by Kumar090680** [comment]
@lsalluri : Note added while completing load and order is captured as Driver Instruction under Instructions Grid in Load and Order Screen as shown below. Working as expected, closing this issue


**BOL-20241118-TEST-01: Completed in App**

![image](https://github.com/user-attachments/assets/351c5982-4b4d-4bff-94c2-7c6570fc4e67)

Instructions given by driver while order completion via mobile app are captured under Instructions grid

![image](https://github.com/user-attachments/assets/09fd3e46-127e-4dd4-ac6c-6ee61d383391)

**ORD-20241118-TEST-02: Completed in App**

![image](https://github.com/user-attachments/assets/932795f0-6125-43fd-bc43-b23a82312757)

![image](https://github.com/user-attachments/assets/d9b35232-8a5e-4f00-bb20-55b9f18e5a97)
