### ISSUE TITLE
Create/edit order - delivery tab redesign to accommodate product category level fueling

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#18]

**Comment by lsalluri** [comment]
FTL Defaults

Autoselect all   compartments of the truck in chart view
Add the current gross from all the   selected compartments and show it in current gross field in chart view
Propogate the same current gross into the   delivered gross and delivered net fields in chart view
Current gross field should be uneditable   in chart view
Delivered gross and delivered net should   be editable in chart view only when a single compartment is selected
Table view should have all compartments   autoselected with an ability to edit the gross and net columns
Current gross field should be uneditable   in table view unless a single compartment is selected in the table
Current gross and current net columns in   the table should be editable for the compartments selected
Delivered gross and delivered net should   be editable in chart view only when a single compartment is selected
Add the current gross from all the   selected compartments and show it in current gross field in table view
Propogate the same current gross into the   delivered gross and delivered net fields in table view
Delivered gross and delivered net should   be editable in table view only when a single compartment is selected

**Comment by lsalluri** [comment]
Need to update Instructions section per FIGMA design as well

**Comment by lsalluri** [comment]
Need to add delivered gross and delivered net columns for FTL and LTL

**Comment by lsalluri** [comment]
Durga the table is allowing me to edit all gross and net values. it should only let me edit the values for the rows that are checked. Also when i am editing something I need to have the ability to close the keyboard. Right now the only way to do that is to click outside of the keyboard and it isn't user friendly. Other than this it looks good.

**Comment by durgaprasadkodecorp** [comment]
@lsalluri you can click the done button to close keyboard or use device back button also
