### ISSUE TITLE
Asset defaults for newly added Number and Barcode fields

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#191]
Pavan or Santosh can give update on the changes being done and what is expected, if there is only 1 asset and 1 tank then default the asset and tank when add all truck or trailer rows are clicked. Previously we were only checking to see if only 1 asset was available at the ship to now we need to check that that only 1 asset with 1 tank is available to default.

**Comment by Kumar090680** [comment]
@lsalluri : Similar issue was already tested and closed #144. Working as expected, closing this issue
