### ISSUE TITLE
Create load - switching between tabs is clearing data

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#2]
See emailed video from 10/14 3 PM IST for the following issues when creating an order from the mobile app

1. In the product tab I selected the first product and added gallons, when I switched to next compartments the product was already chosen and gallons copied from the first compartment but when I saved, it only saved the gasoline compartment. Data shouldn't copy to the 2nd compartment 
2. Moving back to the load tab cleared the BOL number
3. Moving back to the product tab cleared the compartment which was previously saved

**Comment by kpillamyfuelai** [comment]
When compartment is switched, if it is not saved it is not required to hold the data @lsalluri 
Also compartment product will not hold until BOL is commited to the sever and load is recorded
other issues need to be fixed including managing state

**Comment by lsalluri** [comment]
Images are clearing when I switch between tabs and there’s a UI issue with sign tab. Will add to ticket in the morning and assign back to you but just wanted to let you know now.

![Image](https://github.com/user-attachments/assets/2202477e-d361-40dc-adc5-eb6b48ff73d9)

Load and product tabs are no longer clearing so that’s good

Assigning back to you Tulasi
