### ISSUE TITLE
Editing a load that was created in web - compartment info not populating correctly

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#20]
In the product tab of a load (created in web) when i move from one compartment to the next the product changes to what the compartment is set up for but the gallons do not. See attached video for reference.

https://github.com/user-attachments/assets/4b438e7a-401c-426a-87e9-e16916e3d428

**Comment by rbandarukodecorp** [comment]
@lsalluri  Please confirm the below 
1. If Requested gall is more than the available gall, how should we do this validations ?
Ex: Requested Gall 2000
      Available Gall 1500 (Here 500 gal is remaining)
