### ISSUE TITLE
Compartment data not populating when add all truck rows is clicked

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#203]
admin@myfuel.ai
myfuelai2024
order 541

I am trying to add truck rows here for T001 but only getting the first compartment.
![Image](https://github.com/user-attachments/assets/2b4e013a-c772-4f06-b8f5-89882d11c736)

**Comment by sbatharaju12** [comment]
@lsalluri  this is frontend issue i am sending all compatible compartments for that truck but UI side they are taking first compartment 
i am re assigning to @manju45kk

**Comment by Kumar090680** [comment]
All truck's compartments are added in the assets grid when **Add all Truck Compartments** is checked. Working as expected in QA env

**Truck#55 Compartments:**

![image](https://github.com/user-attachments/assets/ced86cb8-0e8f-4b7e-b49c-8b288d8eeaba)

**All Compartments added in Assets grid:**

![image](https://github.com/user-attachments/assets/737abcf5-c0e3-4818-a4ab-9718bf9f4eb4)
