### ISSUE TITLE
Generate Ticket

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#212]
- Add a "Generate Ticket" button to the right of Add Files button
- This button should be enabled when order is in completed status
- When this button is clicked, the delivery ticket should be generated with the completed order information. All time stamps, delivery details, user details etc should remain the same. 
- With the exception of, if any new fees have been added or removed or edited. Those fees should be pulled into the delivery ticket in a fees section. 
- If a delivery ticket has already been generated, then that should remain as is. A new delivery ticket should be generated with the same file name with the time stamp of when the generate ticket was clicked appended to the end of the file name. This is to allow user to be able to differentiate which delivery ticket was generated at the time of order completion and which delivery ticket was generated manually to pull in the fees.

**Comment by dsinghkodecorp** [comment]
Use this endpoint to generate delivery ticket ` v1/generate-delivery-ticket/<int: order_delivery_id>/`

Note: It is order delivery id not Order Id.

e.g

```
curl --location 'http://127.0.0.1:8000/v1/generate-delivery-ticket/358/' \
--header 'Authorization: Bearer <bearer token>'
```

**Comment by Kodecorpui** [comment]
@ added one Button In Documents for completed Orders

**Comment by Kumar090680** [comment]
@Kodecorpui @Vishnu06051999 

@lsalluri : Please re-open this ticket

• Currently generate button is displayed under Generate Button column under Documents grid but, to be available to right of Add Files button as per the above requirement 
• This button is made available only when order is in completed status but, need to available and disabled when order is in New/Fueling/Canceled state
•  Everytime this button under Generate Ticket column is clicked Email Is Triggered to to Customer and ShipTo locations contacts and also new row as shown below is added under Documents grid which is not expected.
• Naming convention of the downloaded Delivery Ticket (when clicked on the file hyperlink under Document column a shown below) and Delivery ticket sent in email was different. But, both naming conventions must be same 
• Currently Fee section is not made available in Delivery ticket so, unable to test these changes. Ticket https://github.com/lsalluri/myfuel.ai/issues/27 is in-progress 

![image](https://github.com/user-attachments/assets/c31a8dfe-539b-4ada-a6fc-fed64183b8ea)
