### ISSUE TITLE
Add BOL ID to load screen in web

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#25]
![Image](https://github.com/user-attachments/assets/b4158115-348d-44f1-ba98-64a368f18ffc)

Add BOL ID to the left of BOL Number. BOL ID is the system generated ID for the load being created. This should be uneditable by the user and should be a required field denoted with an *. The BOL number is only required when the load is in complete status. The * to show the BOL number as required can be removed until the load is in completed status.

**Comment by Kumar090680** [comment]
@sbatharaju12 - System generated Id is appended as shown in below screenshot, seems to be incorrect.

@lsalluri - Currently **Id** and **Number** are available in Load Screen Home Page. As per the issue description, Id to be renamed as **BOL ID** and Number to be renamed as **BOL Number**. Please confirm if my understanding is correct or column names must be retained AS-IS (Id and Number) in Loads Screen Home Page

![Image](https://github.com/user-attachments/assets/db0e431c-604c-4413-aa04-ca87d0b6378e)

![Image](https://github.com/user-attachments/assets/af2de197-97d6-4569-baa0-7b65a6519a23)

**Comment by Kumar090680** [comment]
@lsalluri  - As discussed, right now Id column is available in home page and the same value is displayed in BOL page once order is saved as shown below. And no need to rename Id to BOL ID and Number to BOL Number. Asterisk (*) won't be available for Id column but, is available for loads which are in Complete Status. Closing this issue.

![image](https://github.com/user-attachments/assets/1225c6af-fc18-4f54-91c7-5c3eda93a63e)

**Asterisk (*) not available for load which is in In Progress status**

![image](https://github.com/user-attachments/assets/6fd1e43d-4c1a-40bb-a837-7201247a4f97)

**Asterisk (*) not available for load which is in New statu**s

![image](https://github.com/user-attachments/assets/52eec50d-e4d8-4877-bd48-d0ecba7a0f7f)
