### ISSUE TITLE
Supplier and backup supplier in load screen in web is being removed everytime I open the load

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#26]
Repro steps:

1. Create load with all required fields
2. Exit out of the screen
3. Click back into the load that was previously created - the supplier is now showing blank
4. Need to make sure that the backup terminal and backup supplier are saving and holding as well.

**Comment by Kumar090680** [comment]
@lsalluri - Created a load# BOL_20241016_TEST#2 with Terminal, Supplier, Backup Terminal and Backup Supplier details. When revisited the same load, all the above details are intact. Issue can be closed

**Order created:** 

![Image](https://github.com/user-attachments/assets/09880475-6713-4610-b04c-2e6d52165488)

**Order# in BOL Home Page:**

![Image](https://github.com/user-attachments/assets/a9ee2e8c-1da4-4233-a5f6-241a20ad3b54)

**Order# in BOL Create Page: All details are intact, none are blank**

![Image](https://github.com/user-attachments/assets/d7acb7ad-45be-406f-8eb0-8ec518e1b745)
