### ISSUE TITLE
Time is changing in the order screen after I save and click back into the order in web

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#29]
The original time was 10/15 7:19  PM PST to 10/15 11:19 PM PST (or something like that) when i saved but it changed to a different time once I click back into the same order. The time needs to remain the same as when the order was created.

![Image](https://github.com/user-attachments/assets/c7b40cbe-cbc6-4874-b570-f65bba648dcb)

**Comment by Kumar090680** [comment]
@lsalluri : I created an order# **ORD-TEST-20241016-02** with Start Date/Time (**2024-10-16 18:53**) and End Date/Time (**2024-10-19 18:53**) and same times were retained even after opening back same order. Please check from your side as well. Issue can be closed. 

Start Date/Time (2024-10-16 18:53) and End Date/Time (2024-10-19 18:53) while creating Order# ORD-TEST-20241016-02

![Image](https://github.com/user-attachments/assets/8f4c084b-38c9-4708-b92c-fdbac0c8a889)


Opened the same Order# ORD-TEST-20241016-02 after a while, Start Date/Time and End Date/Time remains intact/same

![Image](https://github.com/user-attachments/assets/c6f15d2b-88d7-4ac3-b7dc-cf3805bb6801)
