### ISSUE TITLE
ProductVariant - API

### ISSUE THREAD

**Issue by kpillamyfuelai** [lsalluri/myfuel.ai#30]
Create List, getbyid and create/update endpoints for ProductVariant

I have added some code and commented it out, please uncomment and use this

One Product can be mapped to one or more products

List -> OriginalProductId, VariantProductId, VariantType, EffectiveStartDate, EffectiveEndDate, IsActive

**Comment by Kumar090680** [comment]
Working as expected. Please refer https://github.com/lsalluri/myfuel.ai/issues/62
