### ISSUE TITLE
Trying to update the driver shift code and save but save is not holding

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#32]
![Image](https://github.com/user-attachments/assets/46cf2ba8-db32-42fb-be9b-746797adefa2)

1. Try to update 0001 to 0004, shows saved successfully but when I click back into the same shift it is still showing 0001.
2. I was able to create 0001 code driver shift twice. See Shift 1 and 4, both have code as 0001 and I didn't not get an error when I created the 2nd one.

**Comment by sbatharaju12** [comment]
This issue was resolved

**Comment by lsalluri** [comment]
I changed the number and code from 4 and 0004 to 5 and 0005 and it worked but when I changed it again to 4 and 0004 I am getting the following error

![Image](https://github.com/user-attachments/assets/6b67983b-af48-477f-bf50-dfff9c2996a0)

**Comment by sbatharaju12** [comment]
i added organization check. now its working fine (fixed)

**Comment by lsalluri** [comment]
This is working correctly now.
