### ISSUE TITLE
Editing an existing compartment's capacity is not allowing me to type and is appending the old with the new

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#33]
![Image](https://github.com/user-attachments/assets/1dfeaf74-2af3-42ba-8cbb-1cb2668e616d)

I added the 3rd compartment and tried to edit the capacity of the 1st compartment to 1000 and I am getting this capacity issue. I believe there is an issue with the current gross and current net fields as well.

**Comment by Kumar090680** [comment]
@lsalluri - Edited truck#**T1980** 2nd compartment's capacity from 1500 to 2700 and it's updating with new value without appending old value. Issue can be closed

**Truck T1980 in Trucks Screen**

![Image](https://github.com/user-attachments/assets/20be6e84-162d-4e4e-827c-e41662ca514a)


**2nd Compartment Capacity, Current Gross and Current Net Old Value - 1500**

![Image](https://github.com/user-attachments/assets/e41aba05-f0af-4c0c-a244-94d285bcb5ee)


**2nd Compartment Capacity, Current Gross and Current Net New Value - 2700**

![Image](https://github.com/user-attachments/assets/b2826600-5227-4445-9d9b-43f6dd6e61d4)
