### ISSUE TITLE
Unable to update the name and description of a product even though the same product does not exist

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#35]
![Image](https://github.com/user-attachments/assets/52c9096d-40ce-4a31-afe7-43d1edeb1d5b)

I only have ULSD #1 created and I am trying to update this product name and description from ULSD 2 to ULSD #2 but system is saying it already exists.

**Comment by lsalluri** [comment]
I am still getting the same issue Santosh

![Image](https://github.com/user-attachments/assets/ca75f5ec-c66f-4c98-9bea-d1465f5b0674)

**Comment by sbatharaju12** [comment]
Above issue was fixed

**Comment by Kumar090680** [comment]
@lsalluri : I created ULSD #2 and ULSD #3 products as below. Closing the issue

![image](https://github.com/user-attachments/assets/c0574b62-a19b-416d-9d9c-5ce9b67f9867)
