### ISSUE TITLE
Truck or trailer with the same VIN number should throw an error

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#37]
Right now if I have the same Number for a truck that already exists, then I am getting the error "TransportUnit with this number already exists". Need the following changes

1. If the same VIN already exists, add error from "TransportUnit with this VIN already exists."
2. If the same Number or VIn are used for a transport unit, only run these duplicate validations on active transport units.

**Comment by sbatharaju12** [comment]
This issue was fixed

**Comment by Kumar090680** [comment]
When Truck or Trailer is created with existing Number/VIN of Active or InActive Truck then, below expected error messages are thrown as expected

Truck **T1980** is **active** Truck in Trucks Screen

![image](https://github.com/user-attachments/assets/355b4078-08bc-4bd5-a7f6-3a351faa8440)

Created Truck with existing (active Truck) VIN, then error "TransportUnit with this VIN already exists" is thrown, as expected.

![image](https://github.com/user-attachments/assets/5f12b79c-4008-4dcd-ba4d-4d6fe07dbb1f)

Created Truck with existing (active Truck) Number, then error "TransportUnit with this number already exists" is thrown, as expected.

![image](https://github.com/user-attachments/assets/b625bb59-0697-47df-9328-b30a99f378be)

Created Trailer with existing (active Truck) Number, then error "TransportUnit with this number already exists" is thrown, as expected.

![image](https://github.com/user-attachments/assets/4630f37e-0631-4ae3-88dd-d3bb58f9d1ea)

Created Trailer with existing (active Truck) VIN, then error "TransportUnit with VIN already exists" is thrown, as expected.

![image](https://github.com/user-attachments/assets/691f53b5-1f92-4f15-8eba-542c6afa7ff5)

Truck **T1981** is  **inactive** Truck in Trucks Screen

![image](https://github.com/user-attachments/assets/b0ab4449-ca12-4b18-a492-966683c04546)

Created Truck with existing (inactive Truck) Number, then error "TransportUnit with this number already exists" is thrown, as expected.

![image](https://github.com/user-attachments/assets/774dca57-74a8-4abc-8c11-e44491f1b6a2)

Created Truck with existing (inactive Truck) VIN, then error "TransportUnit with this VIN already exists" is thrown, as expected.

![image](https://github.com/user-attachments/assets/ead80836-800d-4340-a173-984a453c6aab)

Created Trailer with existing (in active Truck) Number, then error "TransportUnit with this number already exists" is thrown, as expected.

![image](https://github.com/user-attachments/assets/3f1ddbd4-f67d-46ac-8a82-a580549b306f)

Created Trailer with existing (in active Truck) VIN, then error "TransportUnit with VIN already exists" is thrown, as expected.

![image](https://github.com/user-attachments/assets/dbc25e10-5139-421b-91e5-b1cd2ddab9a8)
