### ISSUE TITLE
BOL Number is accepting special characters and blank spaces as the first character/letter. Include field level validations

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#38]
![Image](https://github.com/user-attachments/assets/d5ab90a6-8863-45fa-b13c-424da7f50817)

**Comment by SaiAkhil2** [comment]
Resolve : - TypeField of BOLNumber has to accept first character alphaNumeric from next it tooks Special Characters but not any spaces between

**Comment by Kumar090680** [comment]
@SaiAkhil2 : When special characters @,#,$,%,^,&,*,(,) are entered in the BOL number field as the first character, it's accepting but, upon saving the load BOL Number field is blank i.e., special characters are being removed. 

Currently Order Number field in Order Create Screen is accepting first character as alphanumeric only and then onwards either alphanumeric or only one special character (-)/hyphen and none other special characters are allowed. So, same validation/limitation can be enforced for BOL Number field also. Please check

![image](https://github.com/user-attachments/assets/f8af5bd6-6f52-4ecc-8fe7-83ca4f06217b)

**Comment by SaiAkhil2** [comment]
Resolve -  Bol textfield now accepts as per required (as like as Order Screen)

**Comment by Kumar090680** [comment]
@SaiAkhil2 : Order Number and BOL Number are still accepting special character (-/hyphen) as the first character. And also, BOL number is accepting -,_,# as the special characters but, not Order Number Please refer below.

![image](https://github.com/user-attachments/assets/ed01784b-f68b-43f3-89a7-a252ac43972f)

![image](https://github.com/user-attachments/assets/eccdd708-1ca5-46cd-adeb-f99b252a453f)

![image](https://github.com/user-attachments/assets/38d07476-4af0-4acd-ad87-f316272d6363)

**Comment by Kumar090680** [comment]
Re-opening this issue as BOL Number is still accepting special character as the first character

**Comment by Kumar090680** [comment]
BOL Number is not accepting special character as the first character. Hence closing the ticket
