### ISSUE TITLE
BOL Number is unique. Duplicate BOL Numbers are not allowed

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#39]
![Image](https://github.com/user-attachments/assets/f1f682b2-8bb9-4f9b-839e-9c7910674697)

**Comment by SaiAkhil2** [comment]
Resolve :- Number has to validate from API and while Saving if exist showing error message **(BOL Number is already exist)** getting from the response

**Comment by Kumar090680** [comment]
@SaiAkhil2 : I am able to create duplicate BOL numbers without any pop-message displaying **BOL Number already exists**. Please check

![image](https://github.com/user-attachments/assets/3c405d3f-ab13-40ef-b966-ccc4bf64fa86)

**Comment by Kumar090680** [comment]
I am unable to create duplicate BOL numbers and error message displaying **BOL/Load with this number already exists**. Closing this issue.

**BOL Number **BOL-20241025-TEST-01** already exists**

![image](https://github.com/user-attachments/assets/3b8ad96e-3e85-48b6-b0a2-1f92e0d98259)

**Created BOL Number with existing BOL Number **BOL-20241025-TEST-01** and error is displayed as expected.**

![image](https://github.com/user-attachments/assets/2dd99a48-9ef7-4d90-bd11-19868774340f)
