### ISSUE TITLE
Inactive products and product categories are showing in the order screen product grid section

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#42]
![Image](https://github.com/user-attachments/assets/d2cf6f1d-5121-4593-b247-23e6370b2a08)
![Image](https://github.com/user-attachments/assets/906b7470-e34f-416b-a475-bfb4913f5321)
![Image](https://github.com/user-attachments/assets/a8500f79-4203-4970-8741-a77461fd4bcf)
![Image](https://github.com/user-attachments/assets/e7051516-9a9b-4241-ad77-3bdc63e8fef7)

Lubricants and CONV87OCT is an inactive product category and product but they are still showing in the order screen product grid under product category and product dropdowns

**Comment by Kumar090680** [comment]
@SaiAkhil2  - Still the inactive Product categories are listed in Order Create Screen. Re-assigning this issue back to Akhil

**Inactive Product Categories in Product Categories screen shown below**

![Image](https://github.com/user-attachments/assets/ab0fadac-d9b1-4a63-875a-d29477bca4c5)


**Inactive Product Categories are displayed in Order create screen as shown below**

![Image](https://github.com/user-attachments/assets/5493f913-f06a-4d9b-bf06-cd78d8b93bee)

![Image](https://github.com/user-attachments/assets/48b7e992-e1bc-4988-b0e6-4203e4fe1d0b)

![Image](https://github.com/user-attachments/assets/55990649-115a-4d75-a758-39b1978a285e)


**Inactive Products in Products screen shown below**

![Image](https://github.com/user-attachments/assets/253b15d7-2cc4-41bb-a067-4e6797c8c9b5)


**Inactive Products are displayed in Order create screen as shown below**

![Image](https://github.com/user-attachments/assets/99c3ec0d-b429-4fdf-9104-56c91e66be8d)

**Comment by Kumar090680** [comment]
@SaiAkhil2 : Please find the mismatches in Products and Product Categories. 

**Active Product Categories**:

![image](https://github.com/user-attachments/assets/093d2f62-4af8-4ddc-9313-d8e2d23d3ffe)

**Active Products**:

![image](https://github.com/user-attachments/assets/3ddf9e81-36c1-4def-b74c-9c6ba1b558e5)

![image](https://github.com/user-attachments/assets/5b3496e4-b0db-46a1-aac5-febf08756e81)


1. Description is missing for few Product Categories 
2. Description is missing for few Products
3. Lubricants is active Product Category but, there is no active Product tied to this so, cannot create order as this is mandatory field
4. # Fuel Oil-A category has only 1 active product but, in the order screen many products are displayed in dropdown list
5. ULSD 3 product under Kerosene category is listed and marked active twice in products screen so, displayed twice in the dropdown of order screen also

**Comment by SaiAkhil2** [comment]
Resolve :- Actually Browser not accepted the search Value which start from special Characters , now encode the URL its working fine while search **# Fuel Oil-A**

**Comment by Kumar090680** [comment]
After tagging products to the Propane Category in Products Screen, these appeared in Loads and Orders screen.
Added the missing description and corrected the misspelt product names. Issue resolved.
