### ISSUE TITLE
Inactive products and product categories are showing in the load screen product grid

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#43]
Similar to issue 42

![Image](https://github.com/user-attachments/assets/7fedcd7a-6749-444d-907e-b30fb756f7f1)
![Image](https://github.com/user-attachments/assets/4d36f1ce-9d39-426e-ba36-dbbbdfd1d3b2)
![Image](https://github.com/user-attachments/assets/8584564d-ed27-4b02-8937-320a101b7fcc)

**Comment by Kumar090680** [comment]
@SaiAkhil2 - I still able to view the inactive products and product categories in Loads Create page.

**Inactive Product Categories and Products in respective screens**

![Image](https://github.com/user-attachments/assets/054d55db-d776-47a5-8b82-3dee2ad72edf)

![Image](https://github.com/user-attachments/assets/98a65c34-7667-4ef1-8978-fbb7a8e1a134)

![Image](https://github.com/user-attachments/assets/fbf662be-6a6f-4bd4-a81c-07066a76ce02)


**Inactive Product Categories and Products in Order Create screen**

![Image](https://github.com/user-attachments/assets/e6563689-f531-4de8-811b-0a1f8fba6486)

![Image](https://github.com/user-attachments/assets/70b9d441-b005-4796-b958-2e1e592c947a)

![Image](https://github.com/user-attachments/assets/14136187-236e-48db-b1bf-b39f6fe37596)

![Image](https://github.com/user-attachments/assets/7ddbf356-a2e7-4450-8d78-eba763c3fb44)

**Comment by SaiAkhil2** [comment]
Resolve :- Added is_active=True  params in API's

**Comment by Kumar090680** [comment]
@SaiAkhil2 : Please find the mismatches in Products and Product Categories. 

**Active Product Categories**:

![image](https://github.com/user-attachments/assets/093d2f62-4af8-4ddc-9313-d8e2d23d3ffe)

**Active Products**:

![image](https://github.com/user-attachments/assets/3ddf9e81-36c1-4def-b74c-9c6ba1b558e5)

![image](https://github.com/user-attachments/assets/5b3496e4-b0db-46a1-aac5-febf08756e81)


1. Description is missing for few Product Categories 
2. Description is missing for few Products
3. Lubricants is active Product Category but, there is no active Product tied to this so, cannot create load as this is mandatory field
4. #Fuel Oil-A category has only 1 active product but, in the load screen many products are displayed in dropdown list
5. ULSD 3 product under Kerosene category is listed and marked active twice in products screen so, displayed twice in the dropdown of load screen also

**Comment by SaiAkhil2** [comment]
Resolve :- Actually Browser not accepted the search Value which start from special Characters , now encode the URL its working fine while search **# Fuel Oil-A**

**Comment by Kumar090680** [comment]
@SaiAkhil2 : Please find below observations

1. There are no products tagged to Propane Category (which is an active category in Category screen) in Products Screen but, there must be few products tagged else, creation of load/order cannot be completed since product selection is mandatory
2. Spell check must be done for few product names in Products Screen 
3. Description is missing for few products and categories. Need to add these to make the screen look consistent and good

**Comment by Kumar090680** [comment]
After tagging products to the Propane Category in Products Screen, these appeared in Loads and Orders screen.
Added the missing description and corrected the misspelt product names. Issue resolved.
