### ISSUE TITLE
Terminal search is taking over 30 seconds to load data

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#44]
Terminal search is taking over 30 seconds to load data
![Image](https://github.com/user-attachments/assets/e30011bf-2ffa-48c5-b7eb-3210688a0bbc)

**Comment by sbatharaju12** [comment]
terminal search filter is getting results fast i tested in many times

**Comment by Kumar090680** [comment]
Terminal search is responding in 2 seconds to load data. I searched for **Aircraft** string. Closing this issue


![image](https://github.com/user-attachments/assets/5a8186ea-7e52-482b-b03e-5624240f5f4d)
