### ISSUE TITLE
Only orders and loads in new status should appear in scheduler screen

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#48]
Completed orders and loads are appearing in the scheduler screen right now. Only orders and loads in new status should show in the scheduler.

10/17 2 PM PST: Per Karthik we can change this ticket to disable the user from dragging the completed orders.

**Comment by SaiAkhil2** [comment]
All  Load/Orders are displaying in Scheduler Screen are draggable instead of Status Completed and Cancelled are not to be  draggable

**Comment by Kumar090680** [comment]
I am able to view all statuses (New, In Progress/Fueling, Cancelled and Complete) loads/orders in Scheduler screen. Canceled and Complete loads/orders are disabled with assigning truck/trailer option. Please find screenshots below. Closing this issue

**Orders**

![image](https://github.com/user-attachments/assets/dd33691b-0ac5-42c8-9809-093097f0bd0c)

![image](https://github.com/user-attachments/assets/ea1b52c3-2c3e-4b8d-aba7-df0f3b39e7d2)


**Loads**

![image](https://github.com/user-attachments/assets/2e3a5237-5a51-465c-b366-ebb8e6a49c92)

![image](https://github.com/user-attachments/assets/5bc7dc19-43b5-4294-9fd8-36933eb40b12)
