### ISSUE TITLE
Cancel not working in orders screen

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#49]
I tried cancelling order 1015710 and the status is still in New status

![Image](https://github.com/user-attachments/assets/10e41a81-f4a4-40c0-9ee7-d19c8ccaf223)

**Comment by SaiAkhil2** [comment]
Resolve :- Cancel Label Change into **Back**

**Comment by Kumar090680** [comment]
Closing the issue as it's working as expected

**Order# ORD-TEST-20241018-01 is in New Status**

![image](https://github.com/user-attachments/assets/ba7da356-e31a-4cc8-8fe7-a60831c67b4d)

**Canceled the Order# ORD-TEST-20241018-01, saved and status changed to Canceled Status**

![image](https://github.com/user-attachments/assets/88fa37ae-94d0-42d0-a141-70f00b9ee596)

![image](https://github.com/user-attachments/assets/5338afbe-1ec8-4f49-8c14-49b5da1274a9)
