### ISSUE TITLE
Cancel not working in load screen

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#50]
I tried cancelling a load in new status and it is not changing the status

![Image](https://github.com/user-attachments/assets/cf9d4b55-73e3-4071-a0fd-3798afb7e499)

**Comment by SaiAkhil2** [comment]
Resolve : - Cancel Label Change into **Back**

**Comment by Kumar090680** [comment]
Canceled status is updating in load screen. Working as expected. Closing this issue

**Load# BOL_20241018_TEST#3 in New Status**

![image](https://github.com/user-attachments/assets/4fe8c83f-0400-47b1-a28d-a4874e8f9997)

![image](https://github.com/user-attachments/assets/d4f91cfe-03fd-459c-ade0-02f13abd2991)

**Load# BOL_20241018_TEST#3 is canceled, saved and Status changed to Canceled**

![image](https://github.com/user-attachments/assets/2b28f86e-eeae-4096-9f03-825e62dd8e22)

![image](https://github.com/user-attachments/assets/8caae0f7-e399-4488-9905-af1dcf8ed731)
