### ISSUE TITLE
Add ID column to scheduler before number

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#53]
Add ID column for both order and load to the left of the number column and enable hyperlink so that a user can drag a load which doesn't have BOL number given in the order. Right now the bol number is only mandatory when the load is completed (not when it is in new status) so user is unable to drag a load without the bol number.

**Comment by SaiAkhil2** [comment]
Resolve :- Added ID Column also make it to be draggable to Assign Truck in Scheduler (load without number can access ID to assigned truck)

**Comment by Kumar090680** [comment]
@SaiAkhil2 : ID column is available before Number field but, currently unable to drag and schedule any load/order against T006 active truck which is New/In Progress/Fueling status either by Number or ID.

**Comment by Kumar090680** [comment]
ID column is available before Number field and I am now able to assign load/order to the truck in scheduler. Closing this issue.

![image](https://github.com/user-attachments/assets/e1599a39-777c-46d1-abf1-a949a3f008c8)
