### ISSUE TITLE
Capitalize Id-->ID in Loads Screen

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#54]
![Image](https://github.com/user-attachments/assets/b64805a5-8951-4963-8d87-dfd6674a2430)

**Comment by kc-vamshi** [comment]
Capitalized Id to ID

**Comment by Kumar090680** [comment]
Id field in Loads Screen Home Page is capitalized. Closing this issue

![image](https://github.com/user-attachments/assets/69f793bc-b1e4-4630-8e54-4fd831eb7c41)
