### ISSUE TITLE
Capitalize Id-->ID in Orders Screen

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#55]
![Image](https://github.com/user-attachments/assets/e74fcb84-f311-41ba-9486-75e493dec222)

**Comment by kc-vamshi** [comment]
Capitalized Id to ID

**Comment by Kumar090680** [comment]
Id field in Orders Screen Home Page is capitalized. Closing this issue

![image](https://github.com/user-attachments/assets/f3305bf8-3c41-40a2-8175-2b620ebe8965)
