### ISSUE TITLE
Each duplicate entry in Terminal and Backup Terminal must be appended with address to be unique

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#57]
Duplicate entry must be renamed as **Name - Address**

Example : **IES Downstream LLC** - **666 Kalanianaole Avenue, Hilo, Hawaii, USA, 96720**

![Image](https://github.com/user-attachments/assets/8cf6acfd-473e-48b0-b92d-016856c6b7e7)

**Comment by sbatharaju12** [comment]
added partial terminal API with above requirements

**Comment by Kumar090680** [comment]
@Kodecorpui : As confirmed by Santosh, full address (Address1, Address 2, City, State, Country and Zip) are sent via API but, looks like in UI only Address 1 alone is displayed in Terminal dropdown. Also, same to be implemented for Backup Terminal dropdown 

@lsalluri : Is the below data in **Terminal** dropdown UI will suffice or full address to be displayed in both Terminal and Backup Terminals?

**Terminal** 
![image](https://github.com/user-attachments/assets/d6abcda7-3440-4c33-96a9-e6ddeb974741)

**Backup Terminal**
![image](https://github.com/user-attachments/assets/64d210b1-a019-43da-be3a-afebe53e5617)

**Comment by Kumar090680** [comment]
Working as expected. Closing this issue

Terminal

![image](https://github.com/user-attachments/assets/7b79fe17-5b5d-40f8-b252-26699cd61f6f)

![image](https://github.com/user-attachments/assets/3b7fcdb1-d7ae-4623-b7cf-5ca63788a4c8)

Backup Terminal

![image](https://github.com/user-attachments/assets/e8d06deb-0e3b-4465-a1ec-661249727bc9)

![image](https://github.com/user-attachments/assets/dd0e928e-e578-4c67-b7cc-797a8bece601)
