### ISSUE TITLE
Only active trucks should show up in Scheduler Screen

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#58]

**Comment by Kumar090680** [comment]
@kv-myfuel : I compared Active Trucks in Trucks Screen against Trucks in Scheduler Screen and found out that T0010 and T0011 trucks which are not at all available in Trucks Screen but, are available in Scheduler Screen

**19 Active Trucks in Trucks Screen**:

![image](https://github.com/user-attachments/assets/3366dd0d-e4a6-4c7b-97cf-0176120cda04)

![image](https://github.com/user-attachments/assets/a83d7dc6-5591-45bd-b543-97e674033f58)

**21 Trucks in Scheduler Screen**:

![image](https://github.com/user-attachments/assets/8603b365-92f0-43b9-bbbd-c7b73714ba59)

![image](https://github.com/user-attachments/assets/b9a30808-28fe-4fcd-9116-2f93b0d1a610)

![image](https://github.com/user-attachments/assets/86569673-1d8c-4f55-96d6-0f08a6bc3cb9)

**Comparison of Active Trucks in Trucks Screen Against Trucks in Scheduler Screen**:

![image](https://github.com/user-attachments/assets/94ecf2f6-53ac-4ac5-867c-69a4ef11dcdc)

**Comment by Kumar090680** [comment]
@kv-myfuel : 

1. All active trucks from Trucks screen are shown up in Scheduler as expected.
2. **TL001** is listed as **Trailer** in Trucks screen but, TL001 is displayed both as truck and also as a trailer in Scheduler screen. Please refer below screenshots for reference.

![image](https://github.com/user-attachments/assets/d1b0d8d4-dcd0-49ea-9d20-d4b2034b5aac)

![image](https://github.com/user-attachments/assets/fd6db96c-98a8-45e9-8dac-d78bb79b0475)

**Comment by kv-myfuel** [comment]
@Kumar090680  basically for T0010 and T0011 you didn't check page 2 there this truck are present.
and for next point Trailer coming in Truck list is part of requirement. If we don't to show trailer so please take approval on it

**Comment by Kumar090680** [comment]
@kv-myfuel : Yeah, I am able to view T0010 and T0011 trucks in 2nd page which I missed earlier

@Kodecorpui : As discussed, TL001 is displayed as both Truck and Trailer but, it must be displayed either as Truck or Trailer only. Can you please explain Kritesh to do the necessary changes?

**Comment by kv-myfuel** [comment]
@Kumar090680  as we spoked with Karthik this needs to be combination of truck and trailer 
only change we need to show is its type

**Comment by kc-vamshi** [comment]
@Kumar090680  When there is both Truck and Trailer displaying both.

**Comment by Kumar090680** [comment]
Now Truck and Trailer are displayed with unique icons (whether Trailer is attached to Truck or not). Issue is closed.

![image](https://github.com/user-attachments/assets/2bafe585-a4d0-49fe-9466-d9be9f4c4cde)

![image](https://github.com/user-attachments/assets/c6deadd2-9623-4d94-92b6-8b996ba06ad2)
