### ISSUE TITLE
Column data alignment must be uniform across all screens

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#59]
Currently few columns' data is right aligned, few center aligned and few left aligned. Please make it aligned to left to maintain uniformity across all screens in UI

**Comment by Kodecorpui** [comment]
number is right align, text left align ,  date should be center

**Comment by Kumar090680** [comment]
@Vishnu06051999 : Verified few columns in few screens and found below mismatches. Please implement necessary changes across all screens such that I can verify.


BOL Numbers created as on 22-Oct-2024 are still right aligned instead of left align. Please check

![image](https://github.com/user-attachments/assets/c8683a85-316d-4a60-a5e0-40d97f867f93)

Created a new entry on 22-Oct-2024 in Transfer screen and Zip is center aligned instead of right align

![image](https://github.com/user-attachments/assets/12ea0205-6e96-4cad-98b5-c921eebdee95)

Number and VIN are right aligned in Asset Screen but, these same columns are left aligned in Trucks Screen.

![image](https://github.com/user-attachments/assets/4b9aa31a-fc34-4d50-99a8-0d3acca65ba0)

**Comment by Kumar090680** [comment]
@Vishnu06051999, @Kodecorpui  : Number columns alignment in Fees, DevicePing and Login History Screens are left aligned but, these must be right aligned. Please correct these, rest all looks good.

**Loads Screen**

![image](https://github.com/user-attachments/assets/cd1e1484-1f45-48c7-994b-56bf93419d8b)

**Orders Screen**

![image](https://github.com/user-attachments/assets/830df978-24c1-44ef-84c9-fdc3151c67b4)

**Scheduler Screen**

![image](https://github.com/user-attachments/assets/cdc5263c-21aa-4243-930e-994a0634cd0c)

**Transfer Screen**

![image](https://github.com/user-attachments/assets/dfaf6f71-8636-4e00-a410-093eac6a8b4f)

**Assets Screen**

![image](https://github.com/user-attachments/assets/68d311c4-fcb2-4570-9cee-e0de2107298c)

**Trucks Screen**

![image](https://github.com/user-attachments/assets/753feace-8631-4d16-ad3a-4ae19eda2b13)

**Devices Screen**

![image](https://github.com/user-attachments/assets/c9b2e1e6-ce44-41c3-bdbb-b04883b9ec70)

**Driver Shifts**

![image](https://github.com/user-attachments/assets/ab55aeb6-c526-4676-a239-b5071e912fff)

**Regions Screen**

![image](https://github.com/user-attachments/assets/c8876e28-11e0-437c-b525-a489ef4a70ba)

**Users Screen**

![image](https://github.com/user-attachments/assets/9cc209c3-7091-45cb-be69-39f3a085785b)

**Fees Screen**

![image](https://github.com/user-attachments/assets/d8546bca-12b5-41cc-a878-c05c690764c4)

**Customers Screen**

![image](https://github.com/user-attachments/assets/230c7a9f-fc8a-4a34-9066-533b8fcef380)

**Ship to Screen**

![image](https://github.com/user-attachments/assets/3ba7cdea-d6a3-4265-8772-236c13a63dc4)

**Suppliers Screen**

![image](https://github.com/user-attachments/assets/40416993-0d11-46a5-b45a-511e8df0ef43)

**Terminals Screen**

![image](https://github.com/user-attachments/assets/69fe7d6d-7907-4c47-95f4-3d5d127cd78d)

**Categories Screen**

![image](https://github.com/user-attachments/assets/0f2ac456-a146-41d4-8453-7a2544ec9e3e)

**Products Screen**

![image](https://github.com/user-attachments/assets/e01653c0-24a9-4c48-bc41-a7e59dff914b)

**Variants Screen**

![image](https://github.com/user-attachments/assets/7e265a4e-f849-45c9-91c8-79a3681fc77d)

**DevicePing Screen**

![image](https://github.com/user-attachments/assets/0bca1ae9-49f0-49d0-87de-6dfcb73d153e)

**Login History**

![image](https://github.com/user-attachments/assets/61f3ad6d-4890-43f6-9d43-6f3cdec79ff8)

**Comment by Vishnu06051999** [comment]
@Kumar090680  changed the all screens of grid columns alignment

**Comment by Kumar090680** [comment]
All columns are aligned as per the requirement (number is right align, text left align , date should be center) and also verified below screens which have issues and now columns are aligned as expected. Closing the issue.

**Fees Screen**

![image](https://github.com/user-attachments/assets/fdab18f3-64ef-4b83-8e59-969685ae7546)

**DevicePing Screen**

![image](https://github.com/user-attachments/assets/e6d20958-50e4-477a-a7e9-70f954c30d3b)

**Login History**

![image](https://github.com/user-attachments/assets/84916b0b-9b53-4b98-b6ec-1705c15cf19c)
