### ISSUE TITLE
Inactive records showing - Product Variant

### ISSUE THREAD

**Issue by kpillamyfuelai** [lsalluri/myfuel.ai#62]
1. Do not show inactive product categories and products in Product Variant screen dropdowns
2. Effective Start and End Dates are Date only field, do not show time
3. Effective Start Date - Default it to today for "Add" screen
4. Effective End Date - not required field
5. Variant Type - default it to "similar" for "Add" screen

**Comment by kc-vamshi** [comment]
1. added is_active flag to get only active categories and products
2. removed time field prop
3. added today's date as default in add screen
4. removed Effective End Date from mandatory fields
5. picked "similar" as default variant type after fetching variant types in add screen.

**Comment by Kumar090680** [comment]
@kc-vamshi : All the listed changes are working as expected except below,

1. While creating a new Product Variant, future date selection from Effective Start Date field is disabled but, working fine in Effective End Date

**Comment by kc-vamshi** [comment]
enabled all dates in start date control when there is no end date.

**Comment by Kumar090680** [comment]
@kc-vamshi : Effective Start Date and Effective End Date fields are accepting past dates (older than current sys date). Please check

![image](https://github.com/user-attachments/assets/4dcd6693-cb1a-4ffb-815b-4de28f32f0db)

**Comment by kc-vamshi** [comment]
disabled all dates behind today's date.

**Comment by Kumar090680** [comment]
All the required functionalities are working as expected and date fields are not accepting past date. Issue can be closed.

@kpillamyfuelai, @lsalluri : Please review and close this issue

**Past Dates in Start Date column are disabled and future dates are active**

![image](https://github.com/user-attachments/assets/00bcfc67-3797-4321-aef7-87739772136e)

**Past Dates in End Date column are disabled and future dates are active**

![image](https://github.com/user-attachments/assets/6eaf6d16-a92a-44c1-b762-9b4d05bb52ff)
