### ISSUE TITLE
Product Variant

### ISSUE THREAD

**Issue by kpillamyfuelai** [lsalluri/myfuel.ai#63]
When a new "Product" is added from Product screen, a new record should be inserted into product variant table with the same product as original product and variant product

i.e each product should be mapped to itself

from the UI this shoul;d un-editable

**Comment by sbatharaju12** [comment]
default product variant added and user unable to delete default product variant (fixed)

**Comment by lsalluri** [comment]
@kc-vamshi  I am assigning to you as it looks like Santosh completed backend. Please reach out to him or Karthik if any questions.

**Comment by kc-vamshi** [comment]
@lsalluri Done with the required changes.
1. In add screen when there is a original product it will be checked by default and disabled in products tab grid.
2. In create screen when user selects a original product it will be checked in product tab grid as well.

**Comment by Kumar090680** [comment]
Working as expected. Issue can be closed.

@kpillamyfuelai, @lsalluri : Please review and close this ticket as per my below comments.

When Category is selected from Product Category dropdown, corresponding Products of the selected Category are displayed under **Variants of Selected Category** tab (For example Variants of Kerosene) as shown below

![image](https://github.com/user-attachments/assets/cf4b5d02-444c-463a-9f95-3cff5ff421fb)


Selected product from the dropdown list is auto selected and also disabled (check-box is un-editable) under **Variants of Selected Category** tab as shown below

![image](https://github.com/user-attachments/assets/802910a0-e8b6-4778-b916-259f409f7137)
