### ISSUE TITLE
Canceled load/order shouldn't be able to schedule in Scheduler screen

### ISSUE THREAD

**Issue by Kumar090680** [lsalluri/myfuel.ai#64]
I am able to schedule **Canceled** load/order in Scheduler but, it shouldn't. Please check if any recent changes in the code impacted this earlier working feature.

![Image](https://github.com/user-attachments/assets/7639552c-ef6c-4d58-9867-e29d87ce6694)

![Image](https://github.com/user-attachments/assets/671e4ea4-b0b7-49f6-bbcd-0aae9b1fd0e2)

**Comment by SaiAkhil2** [comment]
Resolve :-  Canceled And Complete Loads/Orders are not to be draggable now, if canceled Order/Load has  Assigned Truck it will show as like  Complete Order/Load in Scheduler instead of dragging again

**Comment by Kumar090680** [comment]
Unable to schedule cancelled and completed load/order. Working as expected
