### ISSUE TITLE
Instructions are duplicating in web and flowing as duplicated to order

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#65]
Order 1018629
suncoast@myfuel.ai
myfuelai2024

![Image](https://github.com/user-attachments/assets/68331b52-dd28-4ff5-9f9a-1eb14e3daff1)
![Image](https://github.com/user-attachments/assets/8d00f90f-107c-4736-a234-2337c50eee54)

**Comment by kc-vamshi** [comment]
sending only edited instructions to prevent creating duplicate instructions.

**Comment by Kumar090680** [comment]
Created an order# **ORD-20241023-TEST-05** with 3 stops each consisting of 5 to 6 instructions. Saved the same order 3 to 4 times and number of instructions retained the same without duplicating. Hence, closing the ticket.
