### ISSUE TITLE
Add new ship to requirement

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#69]
Delivery Images - add another ship to requirement on the order screen in web
![image](https://github.com/user-attachments/assets/1d3d1362-566a-4959-8305-0aa86ad9ee02)

**Comment by adubeykodecorp** [comment]
regarding shipto requirments i need to discuss with kritesh, as i am not getting any request or response format.

**Comment by kc-vamshi** [comment]
@Kumar090680 added one checkbox for Delivery Images

**Comment by Kumar090680** [comment]
**Delivery Images check-box** is now available under Ship To Requirements in Orders Screen. Closing this issue

![image](https://github.com/user-attachments/assets/5f485f93-cf2e-45dc-a0d5-247549b701e0)
