### ISSUE TITLE
Refresh Icon above order grid in scheduler

### ISSUE THREAD

**Issue by kpillamyfuelai** [lsalluri/myfuel.ai#7]

**Comment by Kodecorpui** [comment]
Deployed @kpillamyfuelai @lsalluri  garu please check once

**Comment by Kumar090680** [comment]
@lsalluri  - Refresh button in made available in Scheduler Screen. When refresh button is clicked, Orders/Loads are changed to different colors w.r.t Trucks/Trailers colors as shown below. Issue can be closed.

![Image](https://github.com/user-attachments/assets/c13f96a4-99a3-4aaa-ac97-9a72a5a3b80a)


![Image](https://github.com/user-attachments/assets/511bba7f-4cb9-4d76-adea-51406dd7ab67)
