### ISSUE TITLE
Create new roles - Dispatcher and Accounting

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#70]
Add new roles 
1. Dispatcher - should replicate same permissions as admin for now
2. Accounting - should replicate same permissions as admin for now

![Image](https://github.com/user-attachments/assets/42e286af-49a5-4fba-9a40-959b6dfff543)

**Comment by adubeykodecorp** [comment]
Done. It has no code changes just i have added two new roles from admin panel and mapped with organisation role.

**Comment by adubeykodecorp** [comment]
@lsalluri please verify on server.

**Comment by lsalluri** [comment]
Anuj Please move to QA next time so I can QA first before closing the ticket.

**Comment by lsalluri** [comment]
Looks good.
