### ISSUE TITLE
Fees section in load screen

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#73]
Grid (Fee Name, Quantity, UnitCost, Sub Total)

Quantity should be defaulted to 1 - should be an editable field
Unit Cost should be pulled from the backend - should be an editable field
Sub Total should be Quantity * Unit Cost

Add section to the bottom of the product grid

Please make this reusable so it can be used in the order screen as well.

**Comment by lsalluri** [comment]
![Image](https://github.com/user-attachments/assets/0429d090-6bab-4949-89f6-abb4b0f271ac)

 Need both sections to be similar and aligned. Please add the pagination section to the documents as well to maintain consistency.

**Comment by Kodecorpui** [comment]
@lsalluri  changes Done and deployed

**Comment by Kumar090680** [comment]
@Kodecorpui : Fee grid is added below Product grid as expected. Please find below observations and make necessary changes.

**Empty Space (highlighted in below screenshots) below Product Grid , Documents Grid and Instructions Grid need to be removed and maintain same spacing across grids**

![image](https://github.com/user-attachments/assets/647c342e-98f4-4c72-8cc1-d3f7a3f487f9)

![image](https://github.com/user-attachments/assets/25dc8860-a880-4964-9735-244e13f6f0b9)

**Representation of Pagination to be maintained same across grids**

![image](https://github.com/user-attachments/assets/9ee71f94-3147-4730-9bc3-fbff22f50009)

![image](https://github.com/user-attachments/assets/cb89f7ec-4453-4d0c-82d9-5ba569b1bcdc)

**Comment by Kumar090680** [comment]
@Kodecorpui : Fees grid is added below Product grid as expected and also pagination representation is uniform across various grid sections i.e., Product, Fee, Documents and Instructions as shown below except the extra spacing below Product, Fee and  Documents/Instructions Grids. Can you please check if this extra spacing can be removed to make the screen more aesthetic?
 
**Pagination** 

![image](https://github.com/user-attachments/assets/5bd86dfa-d579-4f89-8bcd-10030c8fb3c6)

![image](https://github.com/user-attachments/assets/b4cf216a-00d3-4e14-a0cc-540fe73e184d)

**Extra Space**

![image](https://github.com/user-attachments/assets/691b5b8a-2094-4924-b788-b8c254071653)

**Comment by Kodecorpui** [comment]
@lsalluri garu Please let me know what you think about these. min-height for all grids or , we remove the height or all of the grids.

**Comment by lsalluri** [comment]
@Kodecorpui  please remove the height until, when data is added we can have a min height for the grid.

**Comment by Kumar090680** [comment]
There is no empty space under Add Product/Add Fee/Documents/Instructions grid in Orders Screen and also height is adjusted as per the records availability in these  grids. Closing this issue

**No empty space before adding records**

![image](https://github.com/user-attachments/assets/cce462a5-14ad-466d-9474-50713f43a158)

**No empty space after adding records**

![image](https://github.com/user-attachments/assets/861eb121-b6d9-4560-8031-5146dd495ff5)

![image](https://github.com/user-attachments/assets/e1d58c6a-b243-47b8-918d-57043555035f)
