### ISSUE TITLE
Search functionality in Loads and Scheduler screens to be implemented based on ID column rather than BOL Number

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#81]
Search functionality in Loads and Scheduler screens to be implemented based on ID column rather than BOL Number, since BOL Number is not mandatory unless load is completed

**Comment by kv-myfuel** [comment]
@Kumar090680  I will add it today

**Comment by sbatharaju12** [comment]
@lsalluri i am implemented search functionality based on ID column in schedular screen rather than (Bol/Order) number

**Comment by Kumar090680** [comment]
@sbatharaju12 : Search functionality in Loads, Orders and Scheduler screens is based on below columns. Except below issue in Scheduler screen, rest are working as expected

Loads Screen - ID Column
Orders Screen - Number and Customer columns
Scheduler Screen - ID Column


**Scheduler Screen - Searched with Order/BOL Number but, error message is displayed. Instead, no results must be displayed similar to Loads and Order Screens**

![Image](https://github.com/user-attachments/assets/2723da8d-a5f0-410e-bf8a-d306f7d1d9ee)

![Image](https://github.com/user-attachments/assets/8d587d5b-b84b-467d-9c7b-b408537ab510)

**Comment by Kumar090680** [comment]
@kc-vamshi : When search in Orders Screen using customer/number columns resulted more than 25 records (which is the current record display in any page), search string is not retained to display rest of the records which exists in other pages

**Comment by kc-vamshi** [comment]
@Kumar090680  previously search query was not going in query params when there is a change in pagination, added it now.

**Comment by Kumar090680** [comment]
All search criteria is working as expected across all screens. Multiple results (more than 25 records) in orders screen are displayed across different pages as expected

**Scheduler Screen - Searched with Order/BOL Number which is not present in this screen, no results are displayed similar to Loads and Order Screens**
![image](https://github.com/user-attachments/assets/6f0505ca-12c8-4856-a249-dfde127f03d9)

**Orders Screen - searched in Orders Screen using customer/number, columns resulted more than 25 records (which is the current record display in any page), search string is retained to display rest of the records which exists in other pages as expected**

![image](https://github.com/user-attachments/assets/b5be47d8-38f5-4871-8f36-09e72eea6d2d)
![image](https://github.com/user-attachments/assets/1496ad6f-cc7d-477f-b011-df82535c2c67)
![image](https://github.com/user-attachments/assets/1593e509-22ec-4947-89c6-df5d866a03bf)

![image](https://github.com/user-attachments/assets/44fdd8b6-97f6-4bfb-991a-0a915fe60d82)
![image](https://github.com/user-attachments/assets/1f7b7564-4548-4591-bbb9-b6e9a7636a7c)
![image](https://github.com/user-attachments/assets/b55b7139-7018-4caf-b7f6-8cb07563dbfc)
