### ISSUE TITLE
CRUD screen for fees

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#82]
CRUD screen for fees
Grid (FeeName, FeeType, UnitCost, IsActive)
Add Edit etc

**Comment by lsalluri** [comment]
Save isn't working on this screen.![Image](https://github.com/user-attachments/assets/4f176b7f-48e2-424d-bb5f-de2e11004625)


Additionally, this type dropdown should only show the following options:
1. Order
2. Load
Type should not be a required field

If order is selected then it should only be a fee available when an order is being created or edited
If load is selected then it should only be a fee available when an order is being created or edited
If no fee type is selected then it should be available for both order and loads

**Comment by Kumar090680** [comment]
@barthakodecorp : Please find below observations in Fees Screen. 

1. In the Fees Screen Grid, **Type** to be renamed as **Fee Type** as per the requirement mentioned above 
2. By default, **Active** to be selected under **Status** field. 
3. Currently, **Fee Name** field is accepting all special characters as the first character.  Field level limitations must be implemented in **Fee Name** field in Create Screen i.e., similar to BOL Number and Order Number

![image](https://github.com/user-attachments/assets/400bde80-8d5a-4f7f-9b13-6d510c862a27)

![image](https://github.com/user-attachments/assets/57c07372-cc42-494b-a9c3-1120c1a57df6)

![image](https://github.com/user-attachments/assets/b480a5e0-226f-4047-8381-8d5dbaec27c5)

**Comment by lsalluri** [comment]
@barthakodecorp  I am continuing to have issues with Save. This is recurring please fix it ASAP. ![Image](https://github.com/user-attachments/assets/ebc58294-8bfe-4946-8ad1-c7884b7d87b6)

Also when I select fee type as order, in the image above I should see Demurrage as an option from the fee dropdown when creating an order. Right now I am seeing Order as an option. ![Image](https://github.com/user-attachments/assets/ba40ebd0-5a37-4658-bb34-1ae67f7d8cf3)

Similarly if I create a fee called Pump Off with a fee type of Load then i should see Pump Off as an option to add to a load.

**Comment by barthakodecorp** [comment]
@lsalluri  your account is not having write permission. So its not allowing to save it. the rest of the issues are fixed.

**Comment by lsalluri** [comment]
Space doesnt work when i try to add a fee name

**Comment by Kumar090680** [comment]
@lsalluri : Fee Name field is not accepting any special characters as the first character and also only hyphen/(-) allowed in this field (similar to BOL Number and Order Number fields in respective screens). So, when you tried using space, Fee Name didn't accept. 

From the screenshot which you pasted above it shows you checked in **Add Instruction** grid so, **Order** is displayed as an option in the dropdown. Instead, if you add an entry under Add Fee grid, all the active fee names added in Fee Screen are displayed in the dropdown. 

Issue can be closed. 


**Create Screen with Active button selected by default**
![image](https://github.com/user-attachments/assets/ce870e31-375b-4b90-bcd5-d8741166a772)

**Need to have Update/Create permissions for the selected user to perform necessary actions.**
![image](https://github.com/user-attachments/assets/1181fde6-5feb-4dda-9ec2-3afca968252c)

**Created Fee Names with Order Fee Type in Fees Screen and these are available in Order screen while adding Fee. Please check below**

![image](https://github.com/user-attachments/assets/2b210f7b-09bf-4eca-b080-4845c7b30065)

**Fee Names in Add Fee grid in Orders Screen**
![image](https://github.com/user-attachments/assets/19567ec9-0b2f-4e23-9528-a574838ac136)
