### ISSUE TITLE
Fees section in order screen

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#86]
Grid (Fee Name, Quantity, UnitCost, Sub Total)

Quantity should be defaulted to 1 - should be an editable field
Unit Cost should be pulled from the backend - should be an editable field
Sub Total should be Quantity * Unit Cost

Add section to the bottom of the documents and instructions section. It should repeat for each stop.

**Comment by kc-vamshi** [comment]
Created Reusable Fee Grid.
Added it in Orders.

**Comment by Kumar090680** [comment]
All the functionalities mentioned are working as expected except below.

@kc-vamshi : Currently there is no option to delete the Fee once added but, if user needs to delete the fee entry, there must be a provision for delete also i.e,, Delete icon similar to Instructions

@sbatharaju12 : Currently only 2 active Fees Names are being displayed in the Fees Name dropdown under Add Fee Grid in Orders Screen though there are 9 active Fees Names relevant to Order Fee Type in Fees Screen.

**Available Fees Names in Add Fee Grid in Orders Screen**

![image](https://github.com/user-attachments/assets/d09452b4-d8f4-4974-a90a-a8eaa6d874c3)

**9 Active Fees Names in Fees Screen**

![image](https://github.com/user-attachments/assets/51ae7f98-ab2d-43ad-84eb-dff2bf21ef09)

**Comment by kc-vamshi** [comment]
@Kumar090680 
Added delete option for new records in Order Fee Grid.

Fee Names: There is possibility of having fees for stops and entire Order as well. As of now we're adding fees for only stops and there are no fee types for "Order Request Stop" but we're receiving fee names of Order in stops. So we might need another fee type or use Order fee types for entire Order including stops. Kritesh is awaiting confirmation on this.

**Comment by Kumar090680** [comment]
@kv-myfuel : Please update comments once you receive confirmation

**Comment by kv-myfuel** [comment]
@Kumar090680 @kc-vamshi Yesterday I spoked with Karthik 
1. Fee type can not be empty
2. whatever fee currently we she in order is for stops only
3. while adding fee it going to be selected as Order which will be considered to be Stop fees only

**Comment by Kumar090680** [comment]
@kv-myfuel : I see in-active Fees also displayed in Orders Screen

Inactive Fees in Fees Screen
![image](https://github.com/user-attachments/assets/c79f48f9-36a2-4f0f-b2a0-ada6db645130)


Inactive Fees under Fee Grid in Orders Screen
![image](https://github.com/user-attachments/assets/a782feea-75e8-4dec-978f-5cd2272565e9)

**Comment by Kumar090680** [comment]
@kv-myfuel : I still see in-active Fees displayed under Fee Grid in Orders Screen


![image](https://github.com/user-attachments/assets/8aa4df51-674d-4eb1-9427-d8db4c6d566b)

**Comment by kv-myfuel** [comment]
@Kodecorpui  please use below api for active records
GET   v1/fee-types/minimal/

**Comment by kc-vamshi** [comment]
@Kumar090680  changed url to show only active fee types.

**Comment by Kumar090680** [comment]
Active Fee Order Types alone are displayed under Fee Grid in Orders Screen. Closing the issue.

**9 Active Fees Order Types in Fees Screen**:

![image](https://github.com/user-attachments/assets/8296229d-1157-412a-93e5-93c93104a22b)

![image](https://github.com/user-attachments/assets/f7fd9094-badf-4645-a5d4-f4a725f6a769)

**9 Active Fees Order Types under Fee Grid in Orders Screen**:

![image](https://github.com/user-attachments/assets/af218450-4dcd-49a8-9499-77bd6f4931cb)

![image](https://github.com/user-attachments/assets/a2a9e036-8925-4a0a-b930-05be74e68238)

**Active Fees suncoast is selected for the order# ORD-20241029-TEST-01**

![image](https://github.com/user-attachments/assets/fc032d27-3344-4c18-af27-5f1f4d564a34)

![image](https://github.com/user-attachments/assets/bd6e0126-68fe-462f-8c85-80894c7285c1)
