### ISSUE TITLE
Ship to and Organization contacts

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#88]
Create a Contacts tab in the Ship To page similar to the Contacts tab in Customer.
Reach out to Kritesh for the API questions

**Comment by sbatharaju12** [comment]
@ backend contacts added to shipto screen (create,update)

**Comment by Vishnu06051999** [comment]
shipto of contacts tab completed(create,update)

**Comment by Kumar090680** [comment]
Contacts Tab in ShipTo Screen is available now and details matched with Customers Screen. Working as expected, closing this issue.

**Contacts Tab in ShipTo Screen**
![image](https://github.com/user-attachments/assets/f746282d-79f9-471c-994b-b9cf4cca9fd3)

**Newly Added ShipTo with Contact details inserted**
![image](https://github.com/user-attachments/assets/85117af8-e463-4d4f-84b5-fd98d888baab)

**Contacts Tab in Customers Screen**
![image](https://github.com/user-attachments/assets/ef223bdc-6175-4627-9955-b2c151d5c0ac)
