### ISSUE TITLE
Add BOL Number field to order screen

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#90]
Add new field BOL Number in the requested products grid
Not a required field. If input, the order and load should be associated with each other.
Please reach out to Kritesh or Santosh to associate the order with load.

**Comment by lsalluri** [comment]
Covered in another ticket.

**Comment by kc-vamshi** [comment]
Added BOL Create through popup in Order Creation.

**Comment by Kumar090680** [comment]
@kc-vamshi : Unable to search the required BOL Number from  **Lookup BOL** dropdown under Attach BOL while adding Product in Order Screen, so unable to associate product with required BOL Number.

@sbatharaju12 : Products associated with Category are not displayed in Add Product grid in Order Screen. Please check.

**Comment by Kumar090680** [comment]
@kc-vamshi : Tried to create an order to associate an existing BOL via Add BOL button but, screen logged out

**Comment by kc-vamshi** [comment]
@Kumar090680 If user is logged out while making any changes, it means user session is expired and need to login again.

**Comment by Kumar090680** [comment]
[Insurance.docx](https://github.com/user-attachments/files/17630342/Insurance.docx)

**Comment by Kumar090680** [comment]
Working as expected. Closing this issue.

[#90 - Retest Pass_Add BOL Number field to order screen.docx](https://github.com/user-attachments/files/17630741/90.-.Retest.Pass_Add.BOL.Number.field.to.order.screen.docx)
