### ISSUE TITLE
Order - Default add rows

### ISSUE THREAD

**Issue by kpillamyfuelai** [lsalluri/myfuel.ai#91]
If truck is selected in the header >

Add Checkbox "Add all Compartments" next to "Assets/Fueling Events" 
If checkbox is checked then get the compartments for the truck and add them to fueling events, default product category and product to selected product category and gross and net to capacity of the truck

**Comment by kpillamyfuelai** [comment]
yes

**Comment by manju45kk** [comment]
Chnages are avilable in Server

**Comment by Kumar090680** [comment]
When Truck is selected, Add All Truck Compartments check-box is made available in Fueling Events and when checked,, truck's all compartments are added to fueling events in ascending order and gross and net are defaulted to truck's capacity. Working as expected.

![image](https://github.com/user-attachments/assets/16f1a4db-9a02-492c-8616-6150af55d968)

![image](https://github.com/user-attachments/assets/d0c844e3-815e-4abb-b3be-aa3845b93bef)

![image](https://github.com/user-attachments/assets/a34a5d67-d45d-4457-b6d0-c62f48a3a3fd)
