### ISSUE TITLE
Load - Default add rows

### ISSUE THREAD

**Issue by kpillamyfuelai** [lsalluri/myfuel.ai#92]
When a truck is selected in the head >

Add Checkbox "Add all Compartments" next to "Add Product" 
If checkbox is checked then get the compartments for the truck and add them to fueling events, default product category and product to selected product category and gross and net to capacity of the truck

**Comment by Kodecorpui** [comment]
@isalluri Added a checkbox  "Add all truck compartments" if the truck is selected, and "Add all trailer compartments" if the trailer is selected.

**Comment by Kumar090680** [comment]
@Kodecorpui : All compartments available for a given truck/trailer are added under the the Product grid but, **order of the compartments are jumbled**. Truck 1986 have compartments 1,2,3 and 4 listed in ascending order in Trucks Screen but, when added to product grid by clicking the check-box, compartment's order is changed. Except this change in order of compartments, rest all working as expected. Please check.

**Add all Truck compartments/Add all Trailer compartments check-box**
![image](https://github.com/user-attachments/assets/d2ffc8f1-f890-4e87-84a9-91bbe101ec60)

**4 Compartments in Truck T1986**
![image](https://github.com/user-attachments/assets/e9880487-0389-41c5-a16a-33b1b575cacd)

**All 4 compartments along with Category, Product, Capacity, Gross and Net  values of the Truck T1986 are added under the Product grid in the Loads Screen upon clicking Add All Truck Compartments check-box**
![image](https://github.com/user-attachments/assets/ac0b662f-a2a8-4f00-b701-37783d323f29)

**Added one more product by clicking the Add Product button and selected the truck T1986's 1st compartment and it allowed to enter remaining Gross and Net values within 5%**
![image](https://github.com/user-attachments/assets/fc06c8c0-4236-453d-9a84-b9ef27033c51)

**3 Compartments in Truck TL001**
![image](https://github.com/user-attachments/assets/c2760f84-15bc-491d-bc07-818d6eb74bb2)

**All 3 compartments along with Category, Product, Capacity, Gross and Net  values of the Truck TL001 are added under the Product grid in the Loads Screen upon clicking Add All Trailer Compartments check-box**
![image](https://github.com/user-attachments/assets/a062bee1-2207-4cd0-b45d-4be1796ae102)

**Added one more product by clicking the Add Product button and selected the truck TL001s compartment#90 and it allowed to enter remaining the Gross and Net values within 5%**
![image](https://github.com/user-attachments/assets/b267f35d-ff50-458a-a1d2-313be119b7c3)

**Comment by Kumar090680** [comment]
Working as expected. Issue can be closed


**Add all Truck Compartments and Add all Trailer Compartments check-boxes are not made available adjacent to Add Product button in BOL screen if Assigned Truck and Assigned Trailer are not selected**

![image](https://github.com/user-attachments/assets/60239fb9-ae9c-4ccb-a01e-904a71cdab72)

**Add all Truck Compartments and Add all Trailer Compartments check-boxes are made available adjacent to Add Product button in BOL screen if Assigned Truck and Assigned Trailer are selected**

![image](https://github.com/user-attachments/assets/f656dc7f-c762-4cb9-a1d8-8f75877a1116)

**Truck T1986 details below**

![image](https://github.com/user-attachments/assets/a2dc4417-23e7-4f0d-a0fa-b978225f9a7a)

**Trailer TL001 details below**

![image](https://github.com/user-attachments/assets/daefa3ad-2e29-411f-8796-f7af25385fea)

**All Truck Compartments are added to Product Grid in the same order as in Trucks Screen ;Product Category and Product in Requested Loads are defaulted to Compartment's Product Category and Product. Gross and Net are defaulted to capacity of the truck's compartment**

![image](https://github.com/user-attachments/assets/f0aac30e-b477-48c3-bcd4-6318e370a2c7)

**All Trailer Compartments are added to Product Grid in the same order as in Trucks Screen ; Product Category and Product in Requested Loads are defaulted to Compartment's Product Category and Product. Gross and Net are defaulted to capacity of the trailer's compartment**

![image](https://github.com/user-attachments/assets/9b7fd9ef-b9b8-423f-b49d-88bfcb3c8b58)
