### ISSUE TITLE
Order screen bugs

### ISSUE THREAD

**Issue by lsalluri** [lsalluri/myfuel.ai#99]
Bar code needs to be input field numeric and not a required field and hidden

**Comment by manju45kk** [comment]
Hi @lsalluri 
i have hide the Barcode Field now  as per the disscussion with @kartik

**Comment by Kumar090680** [comment]
Barcode field is hidden in Orders Screen, when searched (Crtl+F) with **Bar** text didn't result any match. Closing the ticket.

![image](https://github.com/user-attachments/assets/2c661af9-4200-416a-87f6-1f48af4c9267)
